### ISSUE TITLE
teardown routine report "panic: runtime error: slice bounds out of range"

### ISSUE THREAD

**Issue by ypu** [containers/libpod#1172]
/kind bug

**Description**
Podman run or podman rm sometimes report "panic: runtime error: slice bounds out of range" when it try to do clean up and del CNI network. But the command line still can finished with status 0.

**Steps to reproduce the issue:**

1. Run ls with alpine 
# podman --log-level debug run docker.io/library/alpine:latest ls

**Describe the results you received:**
Error msg reported with stack trace

**Describe the results you expected:**
No error msg or stack trace shows up

**Additional information you deem important (e.g. issue happens only occasionally):**

Details of the command line output:

```
#  podman --log-level debug run docker.io/library/alpine:latest ls
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: override_kernelcheck=true           
DEBU[0000] overlay test mount with multiple lowers succeeded 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true 
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
INFO[0000] Found CNI network 99-loopback.conf (type=loopback) at /etc/cni/net.d/99-loopback.conf 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker.io/library/alpine:latest" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] exporting opaque data as blob "sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] exporting opaque data as blob "sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] Using bridge netmode                         
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] exporting opaque data as blob "sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0000] created container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" 
DEBU[0000] container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" has work directory "/var/lib/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata" 
DEBU[0000] container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" has run directory "/var/run/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata" 
DEBU[0000] New container created "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" 
DEBU[0000] container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" has CgroupParent "/libpod_parent/libpod-e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" 
DEBU[0000] Not attaching to stdin                       
DEBU[0000] mounted container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" at "/var/lib/containers/storage/overlay/ff7ca2fedf35c6783a12197100d003a70a6f53133c337f733a4765fac4413a9d/merged" 
DEBU[0000] Created root filesystem for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 at /var/lib/containers/storage/overlay/ff7ca2fedf35c6783a12197100d003a70a6f53133c337f733a4765fac4413a9d/merged 
DEBU[0001] Made network namespace at /var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228 for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
INFO[0001] Got pod network &{Name:agitated_mcnulty Namespace:agitated_mcnulty ID:e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 NetNS:/var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228 PortMappings:[] Networks:[]} 
INFO[0001] About to add CNI network cni-loopback (type=loopback) 
INFO[0001] Got pod network &{Name:agitated_mcnulty Namespace:agitated_mcnulty ID:e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 NetNS:/var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228 PortMappings:[] Networks:[]} 
INFO[0001] About to add CNI network podman (type=bridge) 
DEBU[0001] [0] CNI result: Interfaces:[{Name:cni0 Mac:b6:55:a8:2d:50:77 Sandbox:} {Name:veth78f91256 Mac:9e:a0:ea:0b:ad:a1 Sandbox:} {Name:eth0 Mac:22:b9:1e:7a:2a:c7 Sandbox:/var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228}], IP:[{Version:4 Interface:0xc4204240a8 Address:{IP:10.88.3.153 Mask:ffff0000} Gateway:10.88.0.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:<nil>}], DNS:{Nameservers:[] Domain: Search:[] Options:[]} 
DEBU[0001] Running iptables command: -t filter -I FORWARD -s 10.88.3.153 ! -o 10.88.3.153 -j ACCEPT 
DEBU[0001] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
WARN[0001] failed to parse language "en_US.UTF-8": language: tag is not well-formed 
DEBU[0001] reading hooks from /usr/share/containers/oci/hooks.d 
WARN[0001] failed to load hooks: {}%!(EXTRA *os.PathError=open /usr/share/containers/oci/hooks.d: no such file or directory) 
DEBU[0001] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] exporting opaque data as blob "sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] exporting opaque data as blob "sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab" 
DEBU[0001] Setting CGroup path for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 to /libpod_parent/libpod-e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
DEBU[0001] Created OCI spec for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 at /var/lib/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata/config.json 
DEBU[0001] %s messages will be logged to syslog/usr/libexec/podman/conmon 
DEBU[0001] running conmon: /usr/libexec/podman/conmon    args=[-c e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 -u e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata -p /var/run/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --syslog]
DEBU[0001] Received container pid: 13880                
DEBU[0001] Created container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 in OCI runtime 
DEBU[0001] Attaching to container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
DEBU[0001] connecting to socket /var/run/libpod/socket/e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4/attach 
DEBU[0001] Enabling signal proxying                     
DEBU[0001] Started container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
bin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var
DEBU[0001] Cleaning up container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
DEBU[0001] Running iptables command: -t filter -D FORWARD -s 10.88.3.153 ! -o 10.88.3.153 -j ACCEPT 
DEBU[0001] Tearing down network namespace at /var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228 for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 
INFO[0001] Got pod network &{Name:agitated_mcnulty Namespace:agitated_mcnulty ID:e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4 NetNS:/var/run/netns/cni-33a4e281-6725-2a09-5f8e-b56d05db5228 PortMappings:[] Networks:[]} 
INFO[0001] About to del CNI network podman (type=bridge) 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*chain).teardown(0xc420051bd0, 0xc42000c380, 0x0, 0x0)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/chain.go:87 +0x64b
main.unforwardPorts(0xc42008c140, 0x5c, 0x600)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/portmap.go:317 +0x326
main.cmdDel(0xc4200885b0, 0xc4200143d8, 0x5)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/main.go:114 +0x119
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc42005c140, 0xc4200885b0, 0x833a20, 0xc42006c5d0, 0x583ae0, 0x0, 0xc420051e58)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:175 +0x19f
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc42005c140, 0x583ad8, 0x583ae8, 0x583ae0, 0x833a20, 0xc42006c5d0, 0x57a559, 0x4, 0x0)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:240 +0x1fb
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x583ad8, 0x583ae8, 0x583ae0, 0x833a20, 0xc42006c5d0, 0x57a559, 0x4, 0xc)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:275 +0x118
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x583ad8, 0x583ae8, 0x583ae0, 0x833a20, 0xc42006c5d0, 0x57a559, 0x4)
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:290 +0x7a
main.main()
	/root/go/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/main.go:122 +0x72
ERRO[0001] Error deleting network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input 
ERRO[0001] Error while removing pod from CNI network "podman": netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input 
ERRO[0001] Failed to tear down network namespace for container e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input 
DEBU[0001] unmounted container "e2dea49d8a56465549ef1da2092071917b22eb69bb4b54eb701ef4b986f689c4" 
```

**Output of `podman version`:**

```
Version:       0.7.4-dev
Go Version:    go1.9.1
OS/Arch:       linux/amd64
```

**Comment by mheon** [comment]
Known issue. There is a bug against iptables-go to fix this.

**Comment by mheon** [comment]
https://github.com/coreos/go-iptables/issues/49

Relevant issue

**Comment by mheon** [comment]
This should be fixed now

**Comment by ypu** [comment]
Hi @mheon 
After update the cni plugins and podman update date. The podman run will not panic now. But it still report error message:

```
ERRO[0000] Error deleting network: running [/usr/sbin/iptables -t nat -X CNI-84e70bf16de400e0b9fff0ff --wait]: exit status 4: iptables v1.8.0 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-84e70bf16de400e0b9fff0ff
 
ERRO[0000] Error while removing pod from CNI network "podman": running [/usr/sbin/iptables -t nat -X CNI-84e70bf16de400e0b9fff0ff --wait]: exit status 4: iptables v1.8.0 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-84e70bf16de400e0b9fff0ff
 
ERRO[0000] unable to cleanup network for container 785b9e1086436c28927d1850a60bd31dac9b8274f8049c8e0b05775f94cb70db: "error tearing down CNI namespace configuration for container 785b9e1086436c28927d1850a60bd31dac9b8274f8049c8e0b05775f94cb70db: running [/usr/sbin/iptables -t nat -X CNI-84e70bf16de400e0b9fff0ff --wait]: exit status 4: iptables v1.8.0 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-84e70bf16de400e0b9fff0ff\n"
```

So seems there are still problem. Is there any other package I need update for test this? Or we still need some update in podman?

**Comment by mheon** [comment]
We're waiting on a update to iptables to fix the last few issues. Podman
itself should require no changes.
