### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by crawford** [containers/libpod#1458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**Steps to reproduce the issue:**

Unknown.

**Describe the results you received:**

```
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: panic: close of closed channel
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: goroutine 48 [running]:
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: github.com/projectatomic/libpod/vendor/github.com/docker/docker/pkg/signal.StopCatch(0xc4200dbda0)
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: /builddir/build/BUILD/libpod-07912105635ac54fbf174e394b94899dc23cbf40/_build/src/github.com/projectatomic/libpod/vendor/github.com/docker/docker/pkg/signal/signal.go:26 +0x39
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: main.ProxySignals.func1(0xc4200dbda0, 0xc420372b40)
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: /builddir/build/BUILD/libpod-07912105635ac54fbf174e394b94899dc23cbf40/_build/src/github.com/projectatomic/libpod/cmd/podman/sigproxy.go:28 +0x215
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: created by main.ProxySignals
Sep 13 00:38:14 crawford-libvirt-bootstrap bootkube.sh[896]: /builddir/build/BUILD/libpod-07912105635ac54fbf174e394b94899dc23cbf40/_build/src/github.com/projectatomic/libpod/cmd/podman/sigproxy.go:18 +0xad
```

**Output of `podman version`:**

```
podman version 0.7.3
```

**Output of `podman info`:**

```
host:
  MemFree: 1623007232
  MemTotal: 2096586752
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: crawford-libvirt-master-0
  kernel: 3.10.0-862.14.1.el7.x86_64
  os: linux
  uptime: 10m 15.3s
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Comment by mheon** [comment]
I feel like we fixed this, but I forget exactly when

**Comment by mheon** [comment]
Hm. The issue I'm thinking of was closed in May, which would mean it's prior to 0.7.3 - meaning this is probably a new issue

**Comment by mheon** [comment]
We really need to get a new version into CoreOS so we don't have people running into fixed issues. I'll follow up tomorrow and see where we sit there.

**Comment by vrothberg** [comment]
@mheon, do you have an update regarding this issue?

**Comment by mheon** [comment]
Negative. Couldn't manage to reproduce, and I don't see any obvious cause
in the code

**Comment by vrothberg** [comment]
@mheon, any objections against closing the issue?

**Comment by mheon** [comment]
@vrothberg Agree. @crawford if you can reproduce on 0.9.1 or never, please reopen.
