### ISSUE TITLE
f29: podman run /usr/sbin/int (systemd) fails

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1564]
On Fedora 29 (but not 28):
```
# podman run -ti registry.access.redhat.com/rhel7/rhel:latest /usr/sbin/init
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization other.
Detected architecture x86-64.

Welcome to Red Hat Enterprise Linux Server 7.5 (Maipo)!

Set hostname to <2ddf981e5925>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
Failed to create root cgroup hierarchy: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```
The "Failed to install release agent" line is fine; I get that on f28. The "Failed to create root cgroup hierarchy" and "Failed to allocate manager object" errors are new.

Adding `--cgroup-manager=cgroupfs` makes no difference. (Nor does `=systemd`, which I checked even though it's the default).

podman-0.9.1.1-1.dev.git95dbcad.fc29  but I also tried downgrading all the way down to 0.8.5-5.gitdc5a711. All tested versions of podman fail on f29.  For comparison, all tested versions succeed on f28 (including podman-0.9.1.1-1.dev.git95dbcad.fc28).

**Comment by mheon** [comment]
We needed to add some patches to support starting containers on F29 systemd - I suspect that more patches are required for systemd containers.

**Comment by aalba6675** [comment]
Another data point on F29: `panic: assignment to entry in nil map`

```
$ rpm -q podman oci-systemd-hook runc
podman-0.9.3.1-1.git1cd906d.fc29.x86_64
oci-systemd-hook-0.1.18-1.git38504cc.fc29.x86_64
runc-1.0.0-55.dev.git578fe65.fc29.x86_64
```

I don't even get as far as @edsantiago 

```
podman run --name testing --stop-signal RTMIN+3 --entrypoint /sbin/init --env=container=podman  centos:7
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/containers/libpod/libpod.(*Container).setupOCIHooks(0xc0002ca180, 0x1460920, 0xc000038140, 0xc0000f1500, 0xc, 0xc000528700, 0xc)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/libpod/container_internal.go:1304 +0x3be
github.com/containers/libpod/libpod.(*Container).generateSpec(0xc0002ca180, 0x1460920, 0xc000038140, 0x0, 0xc0005730d8, 0x434df2)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/libpod/container_internal_linux.go:146 +0x24af
github.com/containers/libpod/libpod.(*Container).init(0xc0002ca180, 0x1460920, 0xc000038140, 0xc0002ca180, 0x0)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/libpod/container_internal.go:514 +0x64
github.com/containers/libpod/libpod.(*Container).StartAndAttach(0xc0002ca180, 0x1460920, 0xc000038140, 0xc00026aa80, 0x0, 0x0, 0xc00037ade0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/libpod/container_api.go:181 +0x205
main.startAttachCtr(0xc0002ca180, 0xc00000e018, 0xc00000e020, 0x0, 0x0, 0x0, 0x101, 0x0, 0x0)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/cmd/podman/utils.go:79 +0x22e
main.runCmd(0xc00012e580, 0x0, 0x0)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/cmd/podman/run.go:115 +0x438
github.com/containers/libpod/vendor/github.com/urfave/cli.HandleAction(0x10fdd60, 0x1339d80, 0xc00012e580, 0x0, 0xc000144120)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x12a68c0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12cb3a9, 0x20, 0x0, ...)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:165 +0x459
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc000178a80, 0xc0000300a0, 0xa, 0xa, 0x0, 0x0)
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
        /builddir/build/BUILD/libpod-1cd906da9295304eb7aa2c3d9e75f47b3dd65585/_build/src/github.com/containers/libpod/cmd/podman/main.go:253 +0x148c
```

**Comment by mheon** [comment]
Assignment to nil map in `setupOCIHooks`?

I suppose it could be https://github.com/containers/libpod/blob/52c1365f32398b8ba0321c159e739a5416cd9ab2/libpod/container_internal.go#L1289 - almost certainly is, not that I look at it, given that's the only map in the function.

I suppose it could be a Go versioning thing - maps the map can't be assumed to be initialized anymore? Can easily replaced that with a `make(map[string][]spec.Hook)` which should resolve it.

**Comment by mheon** [comment]
Also, `oci-systemd-hook` should no longer be required by Podman - we've integrated the relevant setup code into Podman itself. It doesn't hurt to have installed, but it should be a no-op now that we're performing the relevant steps before it runs.

**Comment by edsantiago** [comment]
@aalba6675 that podman is known broken. Try 0.9.1.1-1.dev.git95dbcad.fc29

**Comment by edsantiago** [comment]
Confirmed fixed in podman-0.10.1-1.gite4a1553.fc29

**Comment by edsantiago** [comment]
>Also, oci-systemd-hook should no longer be required by Podman

@mheon can you double-check that? With oci-systemd-hook removed, I get the same symptom shown in comment 0.

**Comment by mheon** [comment]
@edsantiago Well that's concerning - we've removed it as a dependency because we integrated the code locally.
@rhatdan looks like we might have missed something?

**Comment by aalba6675** [comment]
Another data point, on F29 I am seeing:

```
# audit2allow -al                                                                                                                                   


#============= container_t ==============

#!!!! This avc is a constraint violation.  You would need to modify the attributes of either the source or target types to allow this access.                             
#Constraint rule:
#       mlsconstrain file { ioctl read lock execute execute_no_trans } ((h1 dom h2 -Fail-)  or (t1 != mcs_constrained_type -Fail-) ); Constraint DENIED                   
mlsconstrain file { write setattr append unlink link rename } ((h1 dom h2 -Fail-)  or (t1 != mcs_constrained_type -Fail-) ); Constraint DENIED                            
mlsconstrain file { create relabelto } ((h1 dom h2 -Fail-)  and (l2 eq h2)  or (t1 != mcs_constrained_type -Fail-) ); Constraint DENIED                                   
mlsconstrain file { relabelfrom } ((h1 dom h2 -Fail-)  or (t1 != mcs_constrained_type -Fail-) ); Constraint DENIED                                                        

#       Possible cause is the source level (s0:c170,c862) and target level (s0:c421,c804) are different.                                                                  
allow container_t container_file_t:file { read write };
```

**Comment by rhatdan** [comment]
This looks like you are attempting to share content between two containers?
Basically one container is attempting to read/write content crreated by another container.

**Comment by aalba6675** [comment]
Ooops my bad - somehow /var/lib/containers was not labeled properly
