### ISSUE TITLE
pypodman doesn't able to list the images on the remote machine.

### ISSUE THREAD

**Issue by praveenkumar** [containers/libpod#1589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

pypodman not able to list the images on the remote instance which is running podman.

**Steps to reproduce the issue:**

## Remote Machine

```
[prkumar@local bin]$ ./minishift ip
192.168.42.97
[prkumar@local bin]$ ./minishift ssh
Last login: Thu Oct  4 01:36:40 2018 from 192.168.42.1
[docker@minishift ~]$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
[docker@minishift ~]$ podman images
REPOSITORY                                 TAG      IMAGE ID       CREATED       SIZE
docker.io/openshift/origin-control-plane   latest   1e2472e9634b   5 hours ago   836MB
docker.io/library/fedora                   latest   c582c1438f27   3 weeks ago   264MB
[docker@minishift ~]$ sudo systemctl status io.podman.socket
Failed to dump process list, ignoring: No such file or directory
* io.podman.socket - Podman Remote API Socket
   Loaded: loaded (/usr/lib/systemd/system/io.podman.socket; enabled; vendor preset: disabled)
   Active: active (listening) since Thu 2018-10-04 01:32:12 EDT; 15min ago
     Docs: man:podman-varlink(1)
   Listen: /run/podman/io.podman (Stream)
   CGroup: /system.slice/io.podman.socket

Oct 04 01:32:12 minishift systemd[1]: Listening on Podman Remote API Socket.
[docker@minishift ~]$ podman version
Version:       0.9.1
Go Version:    go1.10.4
OS/Arch:       linux/amd64
[docker@minishift ~]$ podman info
host:
  Conmon:
    package: podman-0.9.1-3.gitaba58d1.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 1d75f1d54e9e123a97e7f505e38df7ab7192cfa7-dirty'
  MemFree: 192327680
  MemTotal: 4135354368
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 1046200320
  SwapTotal: 1048571904
  arch: amd64
  cpus: 2
  hostname: minishift
  kernel: 4.18.10-200.fc28.x86_64
  os: linux
  uptime: 44m 25.54s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/docker/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/run
```

## Host Machine
```
[prkumar@local ~]$ pypodman --version
pypodman v. 0.9.1

[prkumar@local ~]$ pypodman --user docker --host 192.168.42.97 -i ~/.minishift/machines/minishift/id_rsa images
2018-10-04 11:07:46 IST | CRITICAL | [Errno 104] Connection reset by peer
[prkumar@local ~]$ pypodman --user docker --host 192.168.42.97 -i ~/.minishift/machines/minishift/id_rsa --log-level DEBUG images
2018-10-04 11:08:05 IST | DEBUG    | Logging initialized at level DEBUG
2018-10-04 11:08:05 IST | DEBUG    | Opening tunnel "unix:/run/user/1000/pypodman/podman.socket", cmd "ssh -fNT -v -L /run/user/1000/pypodman/podman.socket:/run/podman/io.podman -i /home/prkumar/.minishift/machines/minishift/id_rsa docker@192.168.42.97"
OpenSSH_7.8p1, OpenSSL 1.1.0i-fips  14 Aug 2018
debug1: Reading configuration data /home/prkumar/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *
debug1: Connecting to 192.168.42.97 [192.168.42.97] port 22.
debug1: Connection established.
debug1: identity file /home/prkumar/.minishift/machines/minishift/id_rsa type 0
debug1: identity file /home/prkumar/.minishift/machines/minishift/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.8
debug1: match: OpenSSH_7.8 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.42.97:22 as 'docker'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32
debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:T3U1d+C6S1+WUWW+WhULT/E6gW5rmHrZT0B3SjSvhdY
debug1: Host '192.168.42.97' is known and matches the ECDSA host key.
debug1: Found key in /home/prkumar/.ssh/known_hosts:263
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,null>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:1000)


debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:1000)


debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:LA7hDAKHZ2ihRodkiaiVcRIf7UjwT4lEFb6BMpyyLR8 /home/prkumar/.ssh/id_rsa
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Offering public key: RSA SHA256:iMTILq7fl6TnilwshALRHFrovMrE3OQHew4v+qlGteQ prkumar@local
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Offering public key: RSA SHA256:bevNzxxYkuf8TyYDZf+bysQVMPQwhWgSGdHop1d2aL0 centos-ci
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Offering public key: RSA SHA256:/Nj0lcaNzCuuUAGr0WR+4Ml7iA5af0lJUv6+XvcoEu4 /home/prkumar/.minishift/machines/minishift/id_rsa
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.42.97 ([192.168.42.97]:22).
debug1: Local connections to /run/user/1000/pypodman/podman.socket:-2 forwarded to remote address /run/podman/io.podman:-2
debug1: Local forwarding listening on path /run/user/1000/pypodman/podman.socket.
debug1: channel 0: new [unix listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: network
debug1: Connection to port -2 forwarding to /run/podman/io.podman port -2 requested.
debug1: channel 1: new [direct-streamlocal@openssh.com]
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /home/docker/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/docker/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
channel 1: open failed: connect failed: open failed
debug1: channel 1: free: direct-streamlocal@openssh.com: listening port -2 for /run/podman/io.podman port -2, connect from  port 0 to /run/user/1000/pypodman/podman.socket port 0, nchannels 2
2018-10-04 11:08:05 IST | DEBUG    | Closing tunnel "unix:/run/user/1000/pypodman/podman.socket"
debug1: channel 0: free: unix listener, nchannels 1
Transferred: sent 4000, received 2896 bytes, in 0.3 seconds
Bytes per second: sent 13937.6, received 10090.8
debug1: Exit status 0
2018-10-04 11:08:05 IST | CRITICAL | [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pypodman/main.py", line 58, in main
    returncode = getattr(obj, args.method)()
  File "/usr/lib/python3.6/site-packages/pypodman/lib/actions/images_action.py", line 56, in list
    self.client.images.list(),
  File "/usr/lib/python3.6/site-packages/pypodman/lib/action_base.py", line 72, in client
    identity_file=self.identity_file)
  File "/usr/lib/python3.6/site-packages/podman/client.py", line 175, in __init__
    if not System(self._client).ping():
  File "/usr/lib/python3.6/site-packages/podman/libs/system.py", line 38, in ping
    with self._client() as podman:
  File "/usr/lib/python3.6/site-packages/podman/client.py", line 125, in __enter__
    self._iface = self._client.open(self._context.interface)
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 550, in open
    self.get_interface(interface_name, socket_connection=connection)
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 590, in get_interface
    desc = _service.GetInterfaceDescription(interface_name)
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 84, in _wrapped
    return self._call(method.name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 141, in _call
    (message, more) = self._next_varlink_message()
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 102, in _next_varlink_message
    message = next(self._next_message())
  File "/usr/lib/python3.6/site-packages/varlink/client.py", line 244, in _next_message
    data = self._connection.recv(8192)
ConnectionResetError: [Errno 104] Connection reset by peer
2018-10-04 11:08:05 IST | INFO     | Review connection arguments for correctness.
2018-10-04 11:08:05 IST | DEBUG    | Closing tunnel "unix:/run/user/1000/pypodman/podman.socket"
```

**Describe the results you received:**

Not able to show the images.

**Describe the results you expected:**

Should able to show the images.

**Comment by TomSweeneyRedHat** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
@praveenkumar "channel 1: open failed: connect failed: open failed" is the issue.  For some reason the ssh channel dropped.  Can you successfully ssh from the Host to the minishift instance?  For testing with VM's I had to setup iptable rules to forward packets from the host to the VM.

**Comment by praveenkumar** [comment]
> For some reason the ssh channel dropped. Can you successfully ssh from the Host to the minishift instance?

@jwhonce yes I can ssh from host to minishift VM without any issue and even execute the commands. In the logs you can see following.

```
$ ./minishift ssh  => this is able to execute and ssh to VM without any issue.
Last login: Thu Oct  4 01:36:40 2018 from 192.168.42.1

[docker@minishift ~]$ cat /etc/redhat-release  => able to execute any commands on the VM
Fedora release 28 (Twenty Eight)

[docker@minishift ~]$ podman images
REPOSITORY                                 TAG      IMAGE ID       CREATED       SIZE
docker.io/openshift/origin-control-plane   latest   1e2472e9634b   5 hours ago   836MB
docker.io/library/fedora                   latest   c582c1438f27   3 weeks ago   264MB
```

**Comment by jwhonce** [comment]
@praveenkumar Can you ssh without using the minishift command or give that command the ssh verbose option so that I may see the ssh login sequence.  Thank you.

**Comment by praveenkumar** [comment]
> Can you ssh without using the minishift command or give that command the ssh verbose option so that I may see the ssh login sequence

@jwhonce here you go, let me know if you need anymore debug stuff.

```
$ ssh -vvv -i ~/.minishift/machines/minishift/id_rsa docker@192.168.42.87
OpenSSH_7.8p1, OpenSSL 1.1.0i-fips  14 Aug 2018
debug1: Reading configuration data /home/prkumar/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug3: /etc/ssh/ssh_config.d/05-redhat.conf line 2: Including file /etc/crypto-policies/back-ends/openssh.config depth 1
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]
debug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]
debug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.42.87 is address
debug2: ssh_connect_direct
debug1: Connecting to 192.168.42.87 [192.168.42.87] port 22.
debug1: Connection established.
debug1: identity file /home/prkumar/.minishift/machines/minishift/id_rsa type 0
debug1: identity file /home/prkumar/.minishift/machines/minishift/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.8
debug1: match: OpenSSH_7.8 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.42.87:22 as 'docker'
debug3: hostkeys_foreach: reading file "/home/prkumar/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
debug2: ciphers stoc: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
debug2: ciphers stoc: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32
debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:qh30isDafzvEyqTtC1yYdigKwO/Z2TkWwjuuhQeGceQ
debug3: hostkeys_foreach: reading file "/home/prkumar/.ssh/known_hosts"
The authenticity of host '192.168.42.87 (192.168.42.87)' can't be established.
ECDSA key fingerprint is SHA256:qh30isDafzvEyqTtC1yYdigKwO/Z2TkWwjuuhQeGceQ.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.42.87' (ECDSA) to the list of known hosts.
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug2: key: /home/prkumar/.minishift/machines/minishift/id_rsa (0x55b863deace0), explicit
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,null>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
Server host/192.168.42.87@REDHAT.COM not found in Kerberos database


debug3: send packet: type 50
debug2: we sent a gssapi-with-mic packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:yx8emMhwn1jXbNKCym8mYmUAte4zt26dZKJtkMhHAog /home/prkumar/.minishift/machines/minishift/id_rsa
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:yx8emMhwn1jXbNKCym8mYmUAte4zt26dZKJtkMhHAog
debug3: sign_and_send_pubkey: RSA SHA256:yx8emMhwn1jXbNKCym8mYmUAte4zt26dZKJtkMhHAog
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.42.87 ([192.168.42.87]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 4
debug1: Remote: /home/docker/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 4
debug1: Remote: /home/docker/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x48
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env QTINC
debug1: Sending env LC_ALL = en_US.utf-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env LS_COLORS
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env MODULES_RUN_QUARANTINE
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env HISTCONTROL
debug3: Ignored env GUESTFISH_RESTORE
debug3: Ignored env HOSTNAME
debug3: Ignored env QTDIR
debug3: Ignored env EDITOR
debug3: Ignored env PATH_modshare
debug3: Ignored env LOADEDMODULES_modshare
debug3: Ignored env GUESTFISH_INIT
debug3: Ignored env XDG_SESSION_ID
debug3: Ignored env MODULES_CMD
debug3: Ignored env USER
debug3: Ignored env ENV
debug3: Ignored env GUESTFISH_PS1
debug3: Ignored env GOPATH
debug3: Ignored env SELINUX_ROLE_REQUESTED
debug3: Ignored env PWD
debug3: Ignored env SSH_ASKPASS
debug3: Ignored env HOME
debug1: Sending env LC_CTYPE = UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env SSH_CLIENT
debug3: Ignored env SELINUX_LEVEL_REQUESTED
debug3: Ignored env BASH_ENV
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env _LMFILES__modshare
debug3: Ignored env LOADEDMODULES
debug3: Ignored env SSH_TTY
debug3: Ignored env MAIL
debug3: Ignored env QTLIB
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env SELINUX_USE_CURRENT_RANGE
debug3: Ignored env SHLVL
debug3: Ignored env MODULEPATH
debug3: Ignored env LOGNAME
debug3: Ignored env DBUS_SESSION_BUS_ADDRESS
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env MODULEPATH_modshare
debug3: Ignored env PATH
debug3: Ignored env _LMFILES_
debug3: Ignored env GUESTFISH_OUTPUT
debug3: Ignored env MODULESHOME
debug3: Ignored env HISTSIZE
debug3: Ignored env CVS_RSH
debug3: Ignored env LESSOPEN
debug3: Ignored env BASH_FUNC_module%%
debug3: Ignored env BASH_FUNC_switchml%%
debug3: Ignored env BASH_FUNC_scl%%
debug3: Ignored env BASH_FUNC__moduleraw%%
debug3: Ignored env _
debug3: Ignored env OLDPWD
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
```

**Comment by jwhonce** [comment]
The machine that you successfully log into is 192.168.42.87 while the failed one is 192.168.42.97.  I would suspect something in the setup/configuration.  I cannot recreate the issue on my local machines.

**Comment by rhatdan** [comment]
I am going to close this since I think this is a configuration issue.
