### ISSUE TITLE
SIGSEGV when using 'podman run --pod="new:<pod-name>" <containerimage>'

### ISSUE THREAD

**Issue by Logibox** [containers/libpod#2124]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using the 'new:..' syntax in --pod, to create a new pod on run, podman panics.

**Steps to reproduce the issue:**

1. `podman pull gcr.io/google_containers/pause-amd64:3.0`
2. `podman run --pod="new:test" gcr.io/google_containers/pause-amd64`

**Describe the results you received:**
```
$ podman run --pod="new:test" gcr.io/google_containers/pause-amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0xc63982]

goroutine 1 [running]:
github.com/containers/libpod/vendor/github.com/containers/image/storage.storageReference.StringWithinTransport(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x152ab60, 0xc000551680, ...)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/storage/storage_reference.go:123 +0x42
github.com/containers/libpod/vendor/github.com/containers/image/storage.storageTransport.ParseStoreReference(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/storage/storage_transport.go:175 +0x333
github.com/containers/libpod/libpod/image.(*Runtime).getImage(0xc000550e20, 0xc00032dfe0, 0x14, 0x0, 0x1523180, 0xc000551640)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/libpod/image/image.go:393 +0x7d
github.com/containers/libpod/libpod/image.(*Image).getLocalImage(0xc000132fc0, 0xc000132fc0, 0xc0005ae3c8, 0x76)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/libpod/image/image.go:230 +0x168
github.com/containers/libpod/libpod/image.(*Runtime).New(0xc000550e20, 0x15359a0, 0xc0000fe048, 0xc00032dfe0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/libpod/image/image.go:136 +0x47d
github.com/containers/libpod/libpod.(*Runtime).createInfraContainer(0xc000142240, 0x15359a0, 0xc0000fe048, 0xc0002fb680, 0x1, 0x0, 0xc0005ae5b8)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/libpod/runtime_pod_infra_linux.go:70 +0xb8
github.com/containers/libpod/libpod.(*Runtime).NewPod(0xc000142240, 0x15359a0, 0xc0000fe048, 0xc000552940, 0x7, 0x8, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/libpod/runtime_pod_linux.go:99 +0x357
main.parseCreateOpts(0x15359a0, 0xc0000fe048, 0xc00018a840, 0xc000142240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/cmd/podman/create.go:544 +0x5c66
main.createContainer(0xc00018a840, 0xc000142240, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/cmd/podman/create.go:144 +0x183
main.runCmd(0xc00018a840, 0x0, 0x0)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/cmd/podman/run.go:53 +0xed
github.com/containers/libpod/vendor/github.com/urfave/cli.HandleAction(0x11a07c0, 0x13fb6d8, 0xc00018a840, 0x0, 0xc0002feb40)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x135c58b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1386b1d, 0x20, 0x0, ...)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:165 +0x459
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc0001dca80, 0xc000104040, 0x4, 0x4, 0x0, 0x0)
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
        /builddir/build/BUILD/libpod-9551f6bb379d4af56dfb63ddf0f3682e40a6694e/_build/src/github.com/containers/libpod/cmd/podman/main.go:263 +0x1577
```

**Describe the results you expected:**

To run the container in the newly created pod.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman --version
podman version 0.12.1.2
```

**Output of `podman info`:**

```
$ podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-1.git9551f6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 67ab7549b44484cc3f201d7bb2b58b922f8edc24'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 40201265152
  MemTotal: 50558132224
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 32212250624
  SwapTotal: 32212250624
  arch: amd64
  cpus: 32
  hostname: myates-uk-rdlabs-hpecorp-net
  kernel: 4.19.13-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 20h 27m 24.2s (Approximately 0.83 days)
insecure registries:
  registries:
  - storex-k8s-1.uk.rdlabs.hpecorp.net:31631
registries:
  registries: null
store:
  ContainerStore:
    number: 34
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/myates/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 13
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This occurs when running rootless.

**Comment by rhatdan** [comment]
$ podman run --pod="new:test" -d fedora sleep 1000

This works for me.  Not sure what you are trying to do.  Of course the tool should not segfault.

**Comment by rhatdan** [comment]
```
# podman run --pod="new:test1" gcr.io/google_containers/pause-amd64
Trying to pull gcr.io/google_containers/pause-amd64...Failed
unable to pull gcr.io/google_containers/pause-amd64: unable to pull image: Error determining manifest MIME type for docker://gcr.io/google_containers/pause-amd64:latest: Error reading manifest latest in gcr.io/google_containers/pause-amd64: manifest unknown: Failed to fetch "latest" from request "/v2/google_containers/pause-amd64/manifests/latest".
```

**Comment by mheon** [comment]
The segfault is somewhere in c/image and happens when creating the infra container

Can you trigger this with `podman pod create` as well as `podman run --pod=new:`?

**Comment by mheon** [comment]
@giuseppe PTAL
