### ISSUE TITLE
cobra panics when running "pod inspect" without parameter

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2681]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
cobra panics when running "pod inspect" without parameter

**Steps to reproduce the issue:**

1. `/home/podman/podman/usr/local/bin/podman pod inspect`
2. `/home/podman/podman/usr/local/bin/podman pod inspect busybox`

**Describe the results you received:**
Step 1 breaks with this error:
```
podman pod inspect
panic: runtime error: index out of range

goroutine 1 [running]:
main.podInspectCmd(0x2a3d900, 0x0, 0x0)
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/cmd/podman/pod_inspect.go:59 +0x407
main.glob..func74(0x289ee60, 0x2a624c8, 0x0, 0x0, 0x0, 0x0)
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/cmd/podman/pod_inspect.go:26 +0x7f
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x289ee60, 0xc00003a0b0, 0x0, 0x0, 0x289ee60, 0xc00003a0b0)
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x289e4e0, 0x28, 0x2a64060, 0xc000752000)
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(0x289e4e0, 0xc0006cc370, 0xc0000ac058)
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/podman/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/cmd/podman/main.go:231 +0x3c
```

**Describe the results you expected:**
The output of step 2

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2684
