### ISSUE TITLE
Regression: 1.2.0:  varlink call unix:/run/podman/io.podman/io.podman.PullImage '{"name": "busybox:foobar"}' crashes

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#2860]
/kind bug

**Description**
PullImage varlink API crashes when remote image tag does not exists

**Steps to reproduce the issue:**

1.  sudo ./bin/podman varlink --timeout 100000000 unix:/run/podman/io.podman

2. $ sudo varlink call unix:/run/podman/io.podman/io.podman.PullImage '{"name": "busybox:foobar"}'

**Describe the results you received:**
The podman command crashes with the following:
``` bash
sudo ./bin/podman varlink --timeout 100000000 unix:/run/podman/io.podman
[sudo] password for kkoukiou: 
ERRO[0006] Error pulling image ref //localhost:5000/busybox:foobar: Error determining manifest MIME type for docker://localhost:5000/busybox:foobar: pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused 
ERRO[0008] Error pulling image ref //busybox:foobar: Error determining manifest MIME type for docker://busybox:foobar: Error reading manifest foobar in docker.io/library/busybox: manifest unknown: manifest unknown 
ERRO[0010] Error pulling image ref //registry.fedoraproject.org/busybox:foobar: Error determining manifest MIME type for docker://registry.fedoraproject.org/busybox:foobar: Error reading manifest foobar in registry.fedoraproject.org/busybox: manifest unknown: manifest unknown 
ERRO[0012] Error pulling image ref //quay.io/busybox:foobar: Error determining manifest MIME type for docker://quay.io/busybox:foobar: Error reading manifest foobar in quay.io/busybox: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n" 
ERRO[0013] Error pulling image ref //registry.access.redhat.com/busybox:foobar: Error determining manifest MIME type for docker://registry.access.redhat.com/busybox:foobar: Error reading manifest foobar in registry.access.redhat.com/busybox: unknown: Not Found 
ERRO[0015] Error pulling image ref //registry.centos.org/busybox:foobar: Error determining manifest MIME type for docker://registry.centos.org/busybox:foobar: Error reading manifest foobar in registry.centos.org/busybox: manifest unknown: manifest unknown 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x218 pc=0x12d0bf5]

goroutine 8 [running]:
github.com/containers/libpod/libpod/image.(*Image).ID(...)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/libpod/image/image.go:287
github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).PullImage.func1(0xc0005bffd0, 0xe, 0xc00091c120, 0xc00000c4c0, 0x0, 0x0, 0xc000139e30, 0xc0000a8e00, 0xc00000c6c0, 0xc000818c00, ...)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/pkg/varlinkapi/images.go:644 +0x4f5
created by github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).PullImage
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/pkg/varlinkapi/images.go:627 +0x208

```

$ bin/podman --version 
podman version 1.2.0

**Comment by KKoukiou** [comment]
cc @baude
