### ISSUE TITLE
Varlink Commit API crashes when ENV parameter is passed to the changes parameter

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#2869]
/kind bug

**Description**

varlink API crashes when ENV is passed into the changes parameter, to set the enviroment variables for the new image

**Steps to reproduce the issue:**

1. $ sudo varlink call unix:/run/podman/io.podman/io.podman.Commit '{"name":"test-sh", "image_name":"testimg:1", "changes":["ENV=sleep 100"]}' 
Error: Varlink Error: Connection Closed

**Describe the results you received:**
``` bash
$ sudo ./bin/podman varlink --timeout 100000000 unix:/run/podman/io.podman
[sudo] password for kkoukiou: 
panic: runtime error: index out of range

goroutine 14 [running]:
github.com/containers/libpod/libpod.(*Container).Commit(0xc0009465a0, 0x18a9a40, 0xc0000b2038, 0xc0005d8110, 0x9, 0x16dab43, 0x2a, 0x0, 0x0, 0x0, ...)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/libpod/container_commit.go:137 +0x2a46
github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).Commit(0xc00000c360, 0xc000946540, 0xc000308000, 0xc0007dc000, 0x0, 0xc0005d80e8, 0x7, 0xc0005d8110, 0x9, 0xc000308080, ...)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/pkg/varlinkapi/images.go:547 +0x313
github.com/containers/libpod/cmd/podman/varlink.(*VarlinkInterface).VarlinkDispatch(0xc000070130, 0xc000946540, 0xc000308000, 0xc0007dc000, 0x0, 0xc0005d802a, 0x6, 0x0, 0x73)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/cmd/podman/varlink/iopodman.go:6073 +0x2a1
github.com/containers/libpod/vendor/github.com/varlink/go/varlink.(*Service).handleMessage(0xc000102630, 0xc000946540, 0xc000308000, 0xc0000b0200, 0x72, 0x73, 0x0, 0x0)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/varlink/go/varlink/service.go:110 +0x1ce
github.com/containers/libpod/vendor/github.com/varlink/go/varlink.(*Service).handleConnection(0xc000102630, 0x18b4540, 0xc00094c090, 0xc000699ff0)
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/varlink/go/varlink/service.go:134 +0x1ad
created by github.com/containers/libpod/vendor/github.com/varlink/go/varlink.(*Service).Listen
	/home/kkoukiou/go/src/github.com/containers/libpod/_output/src/github.com/containers/libpod/vendor/github.com/varlink/go/varlink/service.go:268 +0x28a

```

**Output of `podman version`:**
```
$ ./bin/podman --version
podman version 1.3.0-dev

```

**Comment by KKoukiou** [comment]
cc @baude

**Comment by KKoukiou** [comment]
Oh, my fault, I wanted to use the CMD not ENV. Sorry for the noise.

**Comment by mheon** [comment]
Segfaults are still bad so I vote we reopen and fix

**Comment by rhatdan** [comment]
This should be closed when this PR finally gets merged.
