### ISSUE TITLE
podman-remote pull: SEGV

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2941]
Window 1:
```
# podman varlink --timeout=0 unix:/run/podman/io.podman
```
Window 2:
```
$ sudo ./bin/podman-remote pull alpine                                                                                                                -
ERRO[0000] Could not find flag trace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1243e41]

goroutine 1 [running]:
main.pullCmd(0x2547400, 0x0, 0x0)
        /home/esm/go/src/github.com/containers/libpod/cmd/podman/pull.go:120 +0x291
main.glob..func37(0x24e0d60, 0xc0001a79b0, 0x1, 0x1, 0x0, 0x0)
        /home/esm/go/src/github.com/containers/libpod/cmd/podman/pull.go:35 +0x7f
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x24e0d60, 0xc0000bc080, 0x1, 0x1, 0x24e0d60, 0xc0000bc080)
        /home/esm/go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24e3360, 0x13, 0x2567c60, 0xc0001a6a00)
        /home/esm/go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(0x24e3360, 0xc0006d4370, 0xc0000ae058)
        /home/esm/go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/esm/go/src/github.com/containers/libpod/cmd/podman/main.go:149 +0x3c
```
master @ d10f68ac95e13535f90d9b643ac2d7530178c21d

**Comment by baude** [comment]
i believe this is fixed.

**Comment by edsantiago** [comment]
Cannot reproduce on master; closing.
