### ISSUE TITLE
Error with first podman command, gone after that

### ISSUE THREAD

**Issue by pwFoo** [containers/libpod#3199]
I build podman 1.3.1 and first time a execute a command like `podman ps` I get the following error message.
```
# podman ps
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x7fc42b206000 pc=0x13adf14]

runtime stack:
runtime.throw(0x174b85c, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x139d140, 0xc00070aaa0, 0x1569601)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00070aa70 sp=0xc00070aa38 pc=0x40430b
github.com/containers/libpod/libpod/lock/shm._Cfunc_setup_lock_shm(0x3f19020, 0xc000000800, 0xc0006d724c, 0x0)
        _cgo_gotypes.go:215 +0x4e fp=0xc00070aaa0 sp=0xc00070aa70 pc=0xf949be
github.com/containers/libpod/libpod/lock/shm.CreateSHMLock(0x1712bff, 0xc, 0x800, 0x0, 0x0, 0x0)
        /go/src/github.com/containers/libpod/libpod/lock/shm/shm_lock.go:48 +0xec fp=0xc00070ab50 sp=0xc00070aaa0 pc=0xf94c4c
github.com/containers/libpod/libpod/lock.NewSHMLockManager(0x1712bff, 0xc, 0x800, 0xc0006d7240, 0x0, 0x197e260, 0xc00000ebe0)
        /go/src/github.com/containers/libpod/libpod/lock/shm_lock_manager_linux.go:21 +0x41 fp=0xc00070ab98 sp=0xc00070ab50 pc=0xf96071
github.com/containers/libpod/libpod.makeRuntime(0x19ad980, 0xc0000400a0, 0xc0005d40f0, 0x197e260, 0xc00000ebe0)
        /go/src/github.com/containers/libpod/libpod/runtime.go:923 +0x147c fp=0xc00070b0c8 sp=0xc00070ab98 pc=0x11c7d2c
github.com/containers/libpod/libpod.newRuntimeFromConfig(0x19ad980, 0xc0000400a0, 0x0, 0x0, 0xc00070baf8, 0x0, 0x0, 0xc0005d40f0, 0x0, 0x0)
        /go/src/github.com/containers/libpod/libpod/runtime.go:564 +0x69f fp=0xc00070ba78 sp=0xc00070b0c8 pc=0x11c531f
github.com/containers/libpod/libpod.NewRuntime(...)
        /go/src/github.com/containers/libpod/libpod/runtime.go:355
github.com/containers/libpod/cmd/podman/libpodruntime.getRuntime(0x19ad980, 0xc0000400a0, 0x28c8ce0, 0xc000040000, 0xc00070bd28, 0x415fa9, 0x28c8d00)
        /go/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:149 +0xbf7 fp=0xc00070bc80 sp=0xc00070ba78 pc=0x127d187
github.com/containers/libpod/cmd/podman/libpodruntime.GetRuntime(...)
        /go/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:26
github.com/containers/libpod/pkg/adapter.GetRuntime(0x19ad980, 0xc0000400a0, 0x28c8ce0, 0x21, 0xc000529560, 0xc00070bd88)
        /go/src/github.com/containers/libpod/pkg/adapter/runtime.go:62 +0x4b fp=0xc00070bcd0 sp=0xc00070bc80 pc=0x128af3b
main.psCmd(0x28c8ce0, 0x0, 0x0)
        /go/src/github.com/containers/libpod/cmd/podman/ps.go:214 +0xb0 fp=0xc00070bd70 sp=0xc00070bcd0 pc=0x1368430
main.glob..func10(0x285a2e0, 0x28e6e40, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/containers/libpod/cmd/podman/ps.go:164 +0x86 fp=0xc00070bd98 sp=0xc00070bd70 pc=0x138c296
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x285a2e0, 0xc00000e090, 0x0, 0x0, 0x285a2e0, 0xc00000e090)
        /go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:762 +0x465 fp=0xc00070be80 sp=0xc00070bd98 pc=0x5d4f45
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2863620, 0xc00008ecc0, 0x7fffe19a3f21, 0x6)
        /go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:852 +0x2ec fp=0xc00070bf50 sp=0xc00070be80 pc=0x5d59dc
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/github.com/containers/libpod/cmd/podman/main.go:142 +0x88 fp=0xc00070bf98 sp=0xc00070bf50 pc=0x1353c88
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc00070bfe0 sp=0xc00070bf98 pc=0x42f18c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00070bfe8 sp=0xc00070bfe0 pc=0x45ac71

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/containers/libpod/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x28bf880)
        /go/src/github.com/containers/libpod/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/containers/libpod/vendor/github.com/golang/glog.init.0
        /go/src/github.com/containers/libpod/vendor/github.com/golang/glog/glog.go:410 +0x272

goroutine 10 [runnable]:
github.com/containers/libpod/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00009c410)
        /go/src/github.com/containers/libpod/vendor/github.com/fsnotify/fsnotify/inotify.go:172
created by github.com/containers/libpod/vendor/github.com/fsnotify/fsnotify.NewWatcher
        /go/src/github.com/containers/libpod/vendor/github.com/fsnotify/fsnotify/inotify.go:59 +0x1a8

goroutine 11 [select]:
github.com/containers/libpod/vendor/github.com/cri-o/ocicni/pkg/ocicni.(*cniNetworkPlugin).monitorConfDir(0xc0000be630, 0xc0006d7000)
        /go/src/github.com/containers/libpod/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:144 +0x18c
created by github.com/containers/libpod/vendor/github.com/cri-o/ocicni/pkg/ocicni.initCNI
        /go/src/github.com/containers/libpod/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:236 +0x358
```

Second time it looks good...
```
# podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

Is it a bug or missing environment setup which is fixed during first run and error?

**Comment by pwFoo** [comment]
# podman version
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.5
Git Commit:         7210727e205c333af9a2d0ed0bb66adcf92a6369
Built:              Fri May 24 00:36:05 2019
OS/Arch:            linux/amd64

**Comment by pwFoo** [comment]
After new build and install can't reproduce... Close for now
