### ISSUE TITLE
podman-inspect segfault on infra-container

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3500]
Running podman-inspect on a Pods infra-container has some issues (see below).

### `podman inspect` with useless output

```
[libpod (master)]$ ./bin/podman inspect a67b14bc75de
[
    null
]
```

### `podman inspect --type=container` with segfault
```
[libpod (master)]$ ./bin/podman inspect --type=container a67b14bc75de
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f3 pc=0x1339508]

goroutine 1 [running]:
github.com/containers/libpod/cmd/podman/shared.GetCtrInspectInfo(0xc000529c00, 0xc0000fd680, 0x0, 0xc00027e7e0, 0x0, 0x0)
        cmd/podman/shared/container_inspect.go:132 +0x5d8
main.iterateInput(0x1b9c840, 0xc0000d6018, 0x18cc900, 0xc000445b60, 0x1, 0x2, 0xc000023210, 0x7ffcfd7ada83, 0x9, 0x18d1e36, ...)
        cmd/podman/inspect.go:161 +0x5c0
main.inspectCmd(0x2bf0d00, 0x0, 0x0)
        cmd/podman/inspect.go:118 +0x347
main.glob..func8(0x2b84460, 0xc000445b60, 0x1, 0x2, 0x0, 0x0)
        cmd/podman/inspect.go:37 +0x86
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x2b84460, 0xc0000de060, 0x2, 0x2, 0x2b84460, 0xc0000de060)
        vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b8df60, 0xc0000c6cf0, 0x7ffcfd7ada67, 0xc)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
main.main()
        cmd/podman/main.go:146 +0x88
```

**Comment by mheon** [comment]
It's assuming the create artifact is there.

Unfortunately that is not a safe assumption.

**Comment by mheon** [comment]
Alright, I'm going to self-assign this.

It may be possible to completely eliminate the create artifact. It looks like most of what we use it for is stored in libpod's ContainerConfig and the OCI spec already (though not in a format we can directly use - we'd need to convert it). The few others, we can probably stick in spec annotations for...
