### ISSUE TITLE
varlink: BuildImage() crashes podman if 'more' flag isn't set

### ISSUE THREAD

**Issue by EricHripko** [containers/libpod#3714]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Make a tarball of any image that would succeed at `podman build`

2. Call varlink API without __more__ flag:
  `varlink call unix:///run/podman/io.podman/io.podman.BuildImage '{"build":{"contextDir":"/tmp/dipod-build531627851","dockerfiles":["Dockerfile"]}}'`

**Describe the results you received:**
varlink client prints:
```
Connection closed.
```
podman panics and crashes:
```
panic: runtime error: slice bounds out of range

goroutine 172 [running]:
bytes.(*Buffer).readSlice(0xc000308720, 0xc00009c10a, 0xc000070000, 0x1, 0x0, 0x0, 0xc000070060)
	/usr/local/go/src/bytes/buffer.go:419 +0x10a
bytes.(*Buffer).ReadString(...)
	/usr/local/go/src/bytes/buffer.go:438
github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).BuildImage(0xc0004041e0, 0xc00047c120, 0xc0004821c0, 0xc000160000, 0xc000258040, 0xc0004c8020, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/varlinkapi/images.go:227 +0xd73
github.com/containers/libpod/cmd/podman/varlink.(*VarlinkInterface).VarlinkDispatch(0xc00040a0d0, 0xc00047c120, 0xc0004821c0, 0xc000160000, 0xc000258040, 0xc0004c8020, 0x0, 0xc00049614a, 0xa, 0xc000032000, ...)
	cmd/podman/varlink/iopodman.go:6709 +0x2ace
github.com/varlink/go/varlink.(*Service).HandleMessage(0xc0000d4580, 0xc000160000, 0xc00047c120, 0xc0004821c0, 0xc00011e000, 0x80, 0x81, 0xc00040f740, 0xc000169780)
	vendor/github.com/varlink/go/varlink/service.go:112 +0x266
github.com/varlink/go/varlink.(*Service).handleConnection(0xc0000d4580, 0x1b602a0, 0xc000518000, 0xc00045cfc4)
	vendor/github.com/varlink/go/varlink/service.go:136 +0x1f7
created by github.com/varlink/go/varlink.(*Service).Listen
	vendor/github.com/varlink/go/varlink/service.go:290 +0x1e4
```

**Describe the results you expected:**
Expected some sort of provisional/in-progress response + podman not to crash.

**Additional information you deem important (e.g. issue happens only occasionally):**
Setting __more__ flag (`-m`) prevents the crash.

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.4
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.2
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 6f177c68ed989a6cc14ddbf8cec421819bb46401'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 386330624
  MemTotal: 8300961792
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2145906688
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  hostname: eric-ubuntu
  kernel: 5.0.0-17-generic
  os: linux
  rootless: false
  uptime: 7h 38m 24.3s (Approximately 0.29 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 29
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 66
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Ubuntu box.

**Comment by EricHripko** [comment]
Thank you for fixing this :+1:
