### ISSUE TITLE
varlink: PullImage() crashes podman if an error occurs

### ISSUE THREAD

**Issue by EricHripko** [containers/libpod#3715]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman` crashes if pulling an image results in an error via varlink API.

**Steps to reproduce the issue:**

1. Pick an image name that will fail for your configuration, for example: `alpine:latest`

2. Try to pull it via varlink: `varlink call unix:///run/podman/io.podman/io.podman.PullImage '{"name":"alpine:latest"}'`

**Describe the results you received:**
`podman` crashes:
```
panic: send on closed channel

goroutine 28 [running]:
github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).PullImage.func2(0xc0004a03e0, 0xd, 0xc000512060, 0xc00000e1e0, 0xc0004da098, 0xc0004ec4d0, 0xc00000e440, 0x15a6000, 0x0, 0x0)
	pkg/varlinkapi/images.go:664 +0x1c9
created by github.com/containers/libpod/pkg/varlinkapi.(*LibpodAPI).PullImage
	pkg/varlinkapi/images.go:644 +0x234
```

**Describe the results you expected:**
`podman` not to crash.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens irrespective of whether __more__ flag is set.

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.4
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.2
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 6f177c68ed989a6cc14ddbf8cec421819bb46401'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 386330624
  MemTotal: 8300961792
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2145906688
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  hostname: eric-ubuntu
  kernel: 5.0.0-17-generic
  os: linux
  rootless: false
  uptime: 7h 38m 24.3s (Approximately 0.29 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 29
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 66
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Ubuntu box.

**Comment by EricHripko** [comment]
Thank you for fixing this :+1:
