### ISSUE TITLE
podman-remote: cp crashes

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3861]
All manner of `podman cp` incantations crash. Here's one:
```
$ ./bin/podman varlink --timeout=0 $PODMAN_VARLINK_ADDRESS &
[1] 24403
$ ./bin/podman-remote run --name foo alpine true
ERRO[0008] unable to find flag trace          <!-- would it pretty please be possible
ERRO[0008] unable to find flag authfile       <!-- to get rid of these annoying messages?
ERRO[0008] unable to find flag cgroupns
ERRO[0008] unable to find flag env-host
ERRO[0008] unable to find flag cgroupns
ERRO[0008] unable to find flag http-proxy
ERRO[0008] unable to find flag syslog
$  ./bin/podman-remote cp /etc/services foo:/tmp/                                                                                                      -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130d217]

goroutine 1 [running]:
github.com/containers/libpod/libpod.(*storageService).MountContainerImage(0x0, 0xc000386ec0, 0x40, 0x13f2e30, 0xc000575848, 0xc000000000, 0xc000575848)
        libpod/storage.go:215 +0x37
github.com/containers/libpod/libpod.(*Container).mount(0xc00048acb0, 0x1814768, 0xc00048acb0, 0x176bf3b, 0x5)
        libpod/container_internal.go:1520 +0x5e
github.com/containers/libpod/libpod.(*Container).Mount(0xc00048acb0, 0x0, 0x0, 0x0, 0x0)
        libpod/container_api.go:402 +0x81
main.copyBetweenHostAndContainer(0xc000370f70, 0x7fffb5186b9e, 0xd, 0x7fffb5186bac, 0x9, 0x0, 0x0, 0x0)
        cmd/podman/cp.go:94 +0x324
main.cpCmd(0x28df700, 0x0, 0x0)
        cmd/podman/cp.go:73 +0x10c
main.glob..func11(0x287a7e0, 0xc00034c2c0, 0x2, 0x2, 0x0, 0x0)
        cmd/podman/cp.go:45 +0x86
github.com/spf13/cobra.(*Command).execute(0x287a7e0, 0xc00003c120, 0x2, 0x2, 0x287a7e0, 0xc00003c120)
        vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x2881d60, 0xc0000becf0, 0x7fffb5186b87, 0x13)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
main.main()
        cmd/podman/main.go:148 +0x88
```
podman master @ f618bc3259701fd7d3c1fc90d0ec3812571fa0ab

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by rhatdan** [comment]
@edsantiago I don't see those error messages for podman-remote run?

**Comment by edsantiago** [comment]
>I don't see those error messages for podman-remote run?

They're from the varlink server process; do you have that running in a separate window? They seem to be harmless, and don't affect execution. They have been present since pretty much Day One of podman-remote; see #2212

**Comment by rhatdan** [comment]
These could be indicative of a real bug.  @baude PTAL.

Looks like varlink is attempting to execute commands on behalf of the remote client, but is checking if the fields are valid, against its own CLI.  Should we just ignore these errors or should they be real bugs?

**Comment by QiWang19** [comment]
Do we support podman remote cp already?
My patch has been put off since the non-remote cp are changing for fixing bugs and late review

**Comment by edsantiago** [comment]
>Do we support podman remote cp already?

My point here is that it might be better to say "unsupported" than to dump a giant stack trace.

**Comment by baude** [comment]
if a command is not supported by remote, it should not even show up

**Comment by rhatdan** [comment]
Correct, if this is not ready for support yet, it should be removed from the command line.
