### ISSUE TITLE
podman crashes with multi-stage and incorrect copy --from my-registry/my-image  command

### ISSUE THREAD

**Issue by akram** [containers/libpod#4190]
Hi team, great job,

I faced a crash with a malformed Dockerfile using multistage and:
```
COPY --from quay.io/openshift/origin-cli /usr/bin/oc /usr/bin/oc
```
The malformed command here, is an equal sign missing between from and image name:
it should be
```
COPY --from=quay.io/openshift/origin-cli /usr/bin/oc /usr/bin/oc
```

Here is the stacktrace
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5654a26bfa00, 0x5654a31a3fe0)
	/usr/lib/golang/src/runtime/panic.go:556 +0x2cf fp=0xc0005aff28 sp=0xc0005afe98 pc=0x5654a1309e8f
runtime.panicindex()
	/usr/lib/golang/src/runtime/panic.go:44 +0xfc fp=0xc0005aff58 sp=0xc0005aff28 pc=0x5654a1308b7c
github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Execute(0xc0001dc900, 0x5654a2842320, 0xc00003c108, 0x0, 0x5654a1fdc36f, 0x1, 0xc00025a2c0, 0xc000239e30, 0xc00024e660, 0x23)
	/builddir/build/BUILD/libpod-f60417506b0bd363749b0d32d6ffaced763c71be/_build/src/github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah/build.go:873 +0x1aeb fp=0xc0005b02c0 sp=0xc0005aff58 pc=0x5654a1cd15eb
github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Build(0xc0001dc600, 0x5654a2842320, 0xc00003c108, 0xc0004552c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/libpod-f60417506b0bd363749b0d32d6ffaced763c71be/_build/src/github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah/build.go:1282 +0x6dd fp=0xc0005b04e8 sp=0xc0005b02c0 pc=0x5654a1cd5efd
github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x5654a2842320, 0xc00003c108, 0x5654a2853060, 0xc0001dafc0, 0xc000330120, 0x2d, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/libpod-f60417506b0bd363749b0d32d6ffaced763c71be/_build/src/github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah/build.go:1440 +0x646 fp=0xc0005b0988 sp=0xc0005b04e8 pc=0x5654a1cd6ad6
```

**Comment by rhatdan** [comment]
Best if you open this issue on buildah, since podman is only vendoring in `buildah`.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Closing as I've moved this issue to Buildah at: https://github.com/containers/buildah/issues/1894.  We'll work on it from there.  Thanks for the report @akram !

**Comment by akram** [comment]
Thank you guys!
