### ISSUE TITLE
Segfault when running podman-remote cp

### ISSUE THREAD

**Issue by sshnaidm** [containers/libpod#4203]
/kind bug

**Description**

when running podman-remote with specific arguments it crashes

**Steps to reproduce the issue:**

1. Run `podman-remote  cp /tmp/file1 cont43:/tmp/ccc` where `cont43` is **local** container (not remote) and `/tmp/file1` is an arbitrary file.

**Describe the results you received:**
It crashes:
```
$ podman-remote  cp /tmp/compare_data cont43:/tmp/ccc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556625ab0af9]

goroutine 1 [running]:
panic(0x556626221f40, 0x5566273aafe0)
        /usr/lib/golang/src/runtime/panic.go:565 +0x2c9 fp=0xc00052d6f8 sp=0xc00052d668 pc=0x556624ba3e09
runtime.panicmem(...)
        /usr/lib/golang/src/runtime/panic.go:82
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:390 +0x415 fp=0xc00052d728 sp=0xc00052d6f8 pc=0x556624bb8fc5
github.com/containers/libpod/libpod.(*storageService).MountContainerImage(0x0, 0xc000399180, 0x40, 0x556625b96b60, 0xc00052d848, 0xc000000000, 0xc00052d848)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/libpod/storage.go:215 +0x39 fp=0xc00052d800 sp=0xc00052d728 pc=0x556625ab0af9
github.com/containers/libpod/libpod.(*Container).mount(0xc000106690, 0x55662641caa8, 0xc000106690, 0x556625b9b1fa, 0x5)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/libpod/container_internal.go:1520 +0x60 fp=0xc00052d8f8 sp=0xc00052d800 pc=0x556625a53150
github.com/containers/libpod/libpod.(*Container).Mount(0xc000106690, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/libpod/container_api.go:397 +0x83 fp=0xc00052d930 sp=0xc00052d8f8 pc=0x556625a38003
main.copyBetweenHostAndContainer(0xc0002221a0, 0x7fff78d30ea8, 0x11, 0x7fff78d30eba, 0xf, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/cmd/podman/cp.go:94 +0x326 fp=0xc00052dd00 sp=0xc00052d930 pc=0x556625b3e8f6
main.cpCmd(0x5566274235c0, 0x0, 0x0)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/cmd/podman/cp.go:73 +0x112 fp=0xc00052dd68 sp=0xc00052dd00 pc=0x556625b3e4d2
main.glob..func11(0x5566273be500, 0xc000311a20, 0x2, 0x2, 0x0, 0x0)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/cmd/podman/cp.go:45 +0x88 fp=0xc00052dd90 sp=0xc00052dd68 pc=0x556625b840e8
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x5566273be500, 0xc00003c0e0, 0x2, 0x2, 0x5566273be500, 0xc00003c0e0)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:826 +0x467 fp=0xc00052de78 sp=0xc00052dd90 pc=0x556624d58087
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5566273c5a80, 0xc0000aacf0, 0x7fff78d30e97, 0xd)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:914 +0x2fe fp=0xc00052df50 sp=0xc00052de78 pc=0x556624d58b3e
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/cmd/podman/main.go:148 +0x8a fp=0xc00052df98 sp=0xc00052df50 pc=0x556625b5632a
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:200 +0x214 fp=0xc00052dfe0 sp=0xc00052df98 pc=0x556624ba5b64
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00052dfe8 sp=0xc00052dfe0 pc=0x556624bd13b1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x556626420088, 0x55662741fdd0, 0x1410, 0x1)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc000070fb0 sp=0xc000070f90 pc=0x556624ba5f65
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:307
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:250 +0xbb fp=0xc000070fe0 sp=0xc000070fb0 pc=0x556624ba5dfb
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x556624bd13b1
created by runtime.init.6
        /usr/lib/golang/src/runtime/proc.go:239 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x556626420088, 0x556627420160, 0x140c, 0x1)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc0000717a8 sp=0xc000071788 pc=0x556624ba5f65
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:307
runtime.bgsweep(0xc00004e070)
        /usr/lib/golang/src/runtime/mgcsweep.go:89 +0x138 fp=0xc0000717d8 sp=0xc0000717a8 pc=0x556624b98c08
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000717e0 sp=0xc0000717d8 pc=0x556624bd13b1
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:208 +0x5a

goroutine 4 [finalizer wait]:
runtime.gopark(0x556626420088, 0x55662744a148, 0x140f, 0x1)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc000071f58 sp=0xc000071f38 pc=0x556624ba5f65
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:307
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:175 +0xaa fp=0xc000071fe0 sp=0xc000071f58 pc=0x556624b8f76a
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x556624bd13b1
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:156 +0x63

goroutine 5 [syscall]:
runtime.notetsleepg(0x556627431420, 0x12a05ea91, 0x556625471414)
        /usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000070760 sp=0xc000070730 pc=0x556624b81d68
runtime.timerproc(0x556627431400)
        /usr/lib/golang/src/runtime/time.go:311 +0x2ee fp=0xc0000707d8 sp=0xc000070760 pc=0x556624bc26ee
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000707e0 sp=0xc0000707d8 pc=0x556624bd13b1
created by runtime.(*timersBucket).addtimerLocked
        /usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 52 [GC worker (idle)]:
runtime.gopark(0x55662641ff20, 0xc000423730, 0x556624b71417, 0x0)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc00006d760 sp=0xc00006d740 pc=0x556624ba5f65
runtime.gcBgMarkWorker(0xc000064f00)
        /usr/lib/golang/src/runtime/mgc.go:1836 +0x105 fp=0xc00006d7d8 sp=0xc00006d760 pc=0x556624b93285
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00006d7e0 sp=0xc00006d7d8 pc=0x556624bd13b1
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1784 +0x79
goroutine 10 [syscall]:
runtime.notetsleepg(0x55662744a8a0, 0xffffffffffffffff, 0x0)
        /usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000072f98 sp=0xc000072f68 pc=0x556624b81d68
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:139 +0x9e fp=0xc000072fc0 sp=0xc000072f98 pc=0x556624bb9dce
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc000072fe0 sp=0xc000072fc0 pc=0x556625182ac4
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x556624bd13b1
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x55662641ff20, 0xc000423720, 0x1417, 0x0)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc000073760 sp=0xc000073740 pc=0x556624ba5f65
runtime.gcBgMarkWorker(0xc00005e000)
        /usr/lib/golang/src/runtime/mgc.go:1836 +0x105 fp=0xc0000737d8 sp=0xc000073760 pc=0x556624b93285
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000737e0 sp=0xc0000737d8 pc=0x556624bd13b1
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1784 +0x79

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x55662641ff20, 0xc000326810, 0x1417, 0x0)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc000073f60 sp=0xc000073f40 pc=0x556624ba5f65
runtime.gcBgMarkWorker(0xc000060500)
        /usr/lib/golang/src/runtime/mgc.go:1836 +0x105 fp=0xc000073fd8 sp=0xc000073f60 pc=0x556624b93285
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000073fe0 sp=0xc000073fd8 pc=0x556624bd13b1
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1784 +0x79

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x55662641ff20, 0xc000326820, 0x1417, 0x0)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc00006df60 sp=0xc00006df40 pc=0x556624ba5f65
runtime.gcBgMarkWorker(0xc000062a00)
        /usr/lib/golang/src/runtime/mgc.go:1836 +0x105 fp=0xc00006dfd8 sp=0xc00006df60 pc=0x556624b93285
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00006dfe0 sp=0xc00006dfd8 pc=0x556624bd13b1
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1784 +0x79
goroutine 53 [chan receive]:
runtime.gopark(0x556626420088, 0xc000098538, 0x7f875109170d, 0x3)
        /usr/lib/golang/src/runtime/proc.go:301 +0xf5 fp=0xc0003946d0 sp=0xc0003946b0 pc=0x556624ba5f65
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:307
runtime.chanrecv(0xc0000984e0, 0xc0003947b0, 0xc0004f6701, 0xc0000984e0)
        /usr/lib/golang/src/runtime/chan.go:524 +0x2ee fp=0xc000394760 sp=0xc0003946d0 pc=0x556624b7d1be
runtime.chanrecv2(0xc0000984e0, 0xc0003947b0, 0x55662523349b)
        /usr/lib/golang/src/runtime/chan.go:411 +0x2b fp=0xc000394790 sp=0xc000394760 pc=0x556624b7cebb
github.com/containers/libpod/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x556627421300)
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:990 +0x8d fp=0xc0003947d8 sp=0xc000394790 pc=0x5566256ac9dd
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0003947e0 sp=0xc0003947d8 pc=0x556624bd13b1
created by github.com/containers/libpod/vendor/k8s.io/klog.init.0
        /builddir/build/BUILD/libpod-00057929f5acfd98341964d85722383363376d52/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:404 +0x6e
Aborted (core dumped)
```

**Describe the results you expected:**
This is actually not regular podman-remote usage, but still better not to crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.5.1
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 1406332928
  MemTotal: 25141854208
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 3508535296
  SwapTotal: 12645822464
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: sshnaidm.remote
  kernel: 5.2.15-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 306h 6m 29.61s (Approximately 12.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sshnaidm/.config/containers/storage.conf
  ContainerStore:
    number: 16
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sshnaidm/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 17
  RunRoot: /tmp/1000
  VolumePath: /home/sshnaidm/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
podman-remote-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I think this is fixed upstream

**Comment by sshnaidm** [comment]
@mheon right, checked now with upstream `podman version 1.6.2-dev` and there is no `podman-remote cp` at all. Is it planned to implement?
Closing the issue.

**Comment by mheon** [comment]
We are planning on adding it, but it's not been implemented yet.

**Comment by sshnaidm** [comment]
@mheon cool! It would unblock option to run ansible with podman connection plugin on remote host, because it requires "cp", prepared for it in https://github.com/ansible/ansible/pull/63166
