### ISSUE TITLE
golang varlink getPod fails

### ISSUE THREAD

**Issue by mjudeikis** [containers/libpod#4236]
/kind bug

**Description**

Trying to get pod via golang varlink sdk:
```
	spew.Dump(ppod.Name)
	data, err := iopodman.GetPod().Call(&p.c, ppod.Name)
	var result string
	if err != nil {
		spew.Dump(data)
		spew.Dump(err)
        }
```
Result:
```
(string) (len=15) "default-busybox"
(iopodman.ListPodData) {
 Id: (string) "",
 Name: (string) "",
 Createdat: (string) "",
 Cgroup: (string) "",
 Status: (string) "",
 Labels: (map[string]string) <nil>,
 Numberofcontainers: (string) "",
 Containersinfo: ([]iopodman.ListPodContainerInfo) <nil>
}

(*json.SyntaxError)(0xc00042de40)(unexpected end of JSON input) 
```

Error is : `unexpected end of JSON input`

Where:
```
[root@localhost ~]# varlink call -m unix:/run/podman/io.podman/io.podman.GetPod '{"name": "default-busybox"}'
{
  "pod": {
    "cgroup": "machine.slice",
    "containersinfo": [
      {
        "id": "87cfb81b2ee8b5be0e0db68dc0a073935daf393b8d9caf7d9bbb2e33d4084125",
        "name": "nginx",
        "status": "exited"
      }
    ],
    "createdat": "2019-10-11T14:08:17+01:00",
    "id": "cf744313950366a2f63b4cecd30163443cd3e6a8e452acc051c319aee75882e8",
    "name": "default-busybox",
    "numberofcontainers": "1",
    "status": "Exited"
  }
}
```
I dont see anything wrong in generated SDK too.
```
func (m GetPod_methods) Send(c *varlink.Connection, flags uint64, name_in_ string) (func() (ListPodData, uint64, error), error) {
	var in struct {
		Name string `json:"name"`
	}
	in.Name = name_in_
	receive, err := c.Send("io.podman.GetPod", in, flags)
	if err != nil {
		return nil, err
	}
	return func() (pod_out_ ListPodData, flags uint64, err error) {
		var out struct {
			Pod ListPodData `json:"pod"`
		}
		flags, err = receive(&out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		pod_out_ = out.Pod
		return
	}, nil
}
```

I see that error comes from `lags, err = receive(&out)`
And its not always, it might be some race condition in API :/ 

**Output of `podman version`:**

```
[root@localhost ~]# podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 721313792
  MemTotal: 16449830912
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 858779648
  SwapTotal: 6442446848
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.2.16-200.fc30.x86_64
  os: linux
  rootless: false
  uptime: 162h 24m 27.23s (Approximately 6.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by mjudeikis** [comment]
```
	return func() (pod_out_ ListPodData, flags uint64, err error) {
		var out struct {
			Pod ListPodData `json:"pod"`
		}
		flags, err = receive(&out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		pod_out_ = out.Pod
		time.Sleep(1 * time.Second)
		return
	}, nil
```

Adding sleep before the empty return. I think this might be async calls and the fact that we use pointers....

**Comment by baude** [comment]
@mjudeikis I am able to make this work.  Here is a sample snippet:

```
package main

import (
	"fmt"
	"os"

	"github.com/baude/4236/iopodman"
	"github.com/varlink/go/varlink"
)

func exitOnError(err error) {
	fmt.Println(err)
	os.Exit(1)
}
func main() {
	address := "unix:/run/podman/io.podman"
	conn, err := varlink.NewConnection(address )
	if err != nil {
		exitOnError(err)
	}

	pod, err := iopodman.GetPod().Call(conn, "foobar")
	if err != nil {
		exitOnError(err)
	}
	fmt.Println(pod.Id)
}
```
I did copy the generated iopodman.go file from libpod and also the vendor directories as well.  Could you try similar? Or point to a repo or tarball with your tree?

**Comment by mjudeikis** [comment]
@baude It works on my end, but as soon as I do more operations on same varlink connection - it gets crazy and start dropping me errors like this:
```
panic: runtime error: slice bounds out of range                                                                                                                                                                                               
                                                                                                                                                                                                                                              
goroutine 178 [running]:                                                                                                                                                                                                                      
bufio.(*Reader).ReadSlice(0xc0004e45a0, 0xc000106300, 0xc000430ae0, 0xc000579f90, 0xc000579f00, 0x3, 0x0)                                                                                                                                     
        /home/mjudeiki/.gvm/gos/go1.12.10/src/bufio/bufio.go:331 +0x22e                                                                                                                                                                       
bufio.(*Reader).ReadBytes(0xc0004e45a0, 0xc000579f00, 0x4a, 0x50, 0x433ed6, 0x1506860, 0x0)                                                                                                                                                   
        /home/mjudeiki/.gvm/gos/go1.12.10/src/bufio/bufio.go:434 +0x70                                                                                                                                                                        
github.com/varlink/go/varlink/internal/ctxio.(*Conn).ReadBytes.func1(0xc0004d09e0, 0x0, 0xc000106360)                                                                                                                                         
        /home/mjudeiki/go1.12/pkg/mod/github.com/varlink/go@v0.0.0-20191018142704-4ecdbb8a36c2/varlink/internal/ctxio/conn.go:91 +0x3c                                                                                                        
created by github.com/varlink/go/varlink/internal/ctxio.(*Conn).ReadBytes                                                                                                                                                                     
        /home/mjudeiki/go1.12/pkg/mod/github.com/varlink/go@v0.0.0-20191018142704-4ecdbb8a36c2/varlink/internal/ctxio/conn.go:90 +0xce
```

What is the recommendation? use the same connection or create new ones for each call/goroutine?
I think its race-condition somewhere. as  with single operations I didnt had any issues

**Comment by mjudeikis** [comment]
so Im reusing one connection in multiple goroutines.
And it is failing a lot.

Added mutex for each call in my abstraction:
```
type conn struct {
	varlink.Connection
	sync.Mutex
}
```

and 
```
p.c.Lock()
podmanPodName, err := iopodman.CreatePod().Call(ctx, &p.c.Connection, *podmanPod)
p.c.Unlock()
```

And from the first look looks like it works.

**Comment by rhatdan** [comment]
@baude @jwhonce Are you guys going to fix this?
