### ISSUE TITLE
--userns=keep-id not working

### ISSUE THREAD

**Issue by leorochael** [containers/libpod#4242]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Can't get a pretty standard container to run rootless with `--user-ns=keep-id`.

Running rootless:

```
$ podman run --rm -ti -v /tmp:/tmp --entrypoint='["/sbin/my_init", "--"]' docker.io/phusion/baseimage:latest-amd64 bash
Trying to pull docker.io/phusion/baseimage:latest-amd64...
Getting image source signatures
Copying blob 05731e63f211 done
Copying blob 6abc03819f3e done
Copying blob 98a76ea5b74b done
Copying blob 0bd67c50d6be done
Copying blob 17346ba167b8 done
Copying blob b149b4fd3dc6 done
Copying config ef6863d3b1 done
Writing manifest to image destination
Storing signatures
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct 11 17:00:04 93f3b9eeee4e syslog-ng[15]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 24
*** Running bash...
Oct 11 17:00:05 93f3b9eeee4e cron[28]: (CRON) INFO (pidfile fd = 3)
Oct 11 17:00:05 93f3b9eeee4e cron[28]: (CRON) INFO (Running @reboot jobs)
root@93f3b9eeee4e:/# echo it's running
it's running
```

Running rootless with `--userns=keep-id`:

```
$ podman run --userns=keep-id --rm -ti -v /tmp:/tmp --entrypoint='["/sbin/my_init", "--"]' docker.io/phusion/baseimage:latest-amd64 bash
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 414, in <module>
    main(args)
  File "/sbin/my_init", line 330, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 90, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 74, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

**Steps to reproduce the issue:**

1. Run:

 - `podman run --rm -ti -v /tmp:/tmp --entrypoint='["/sbin/my_init", "--"]' docker.io/phusion/baseimage:latest-amd64 bash`

2. See that it works and exit the container

3. Then run

 - `podman run --userns=keep-id --rm -ti -v /tmp:/tmp --entrypoint='["/sbin/my_init", "--"]' docker.io/phusion/baseimage:latest-amd64 bash`

4. Check that it doesn't work.

**Describe the results you received:**

Permission denied message. Looks like the running container root user cannot read files that are supposed to belong to the root user in the image.

**Describe the results you expected:**

I expected the `--userns=keep=id` parameter to work like running without it, except mapping my user to the same `uid` inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using podman from ppa in Ubuntu 18.04, with the `overlay` driver and a `fuse-overlayfs` binary I compiled from source.

**Output of `podman version`:**

```
$ podman --version
podman version 1.6.1
WARN[0000] unable to find /home/bb/.config/containers/registries.conf. some podman (image shortnames) commands may be limited
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 2148642816
  MemTotal: 33594552320
  OCIRuntime:
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: ger-nt-dev-301
  kernel: 5.0.0-29-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.1
      commit: unknown
  uptime: 93h 43m 26.31s (Approximately 3.88 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/bb/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /home/bb/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 0.6.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.31
  GraphRoot: /home/bb/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
  VolumePath: /home/bb/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/bionic,now 1.6.1-1~ubuntu18.04~ppa3 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 18.04 running on physical notebook

**Comment by rhatdan** [comment]
Is /etc/container_environment readable my your user?  IE a non root user?

**Comment by giuseppe** [comment]
you can workaround this specific issue adding the DAC_OVERRIDE capability.  Keep in mind that by default running as root keeps some capabilities that are not maintained when running with uid != 0 inside of the container.

```
$ podman run --rm fedora getpcaps 1
Capabilities for `1': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
$ podman run --user 1000 --rm fedora getpcaps 1
Capabilities for `1': =
```

**Comment by giuseppe** [comment]
I am closing the issue since I think it is working as expected
