### ISSUE TITLE
podman build panics with SIGSEGV when passed a file instead of a folder

### ISSUE THREAD

**Issue by timonegk** [containers/libpod#4383]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman build` fails when it is called with a file instead of a directory.

**Steps to reproduce the issue:**

```
touch file
podman build file
```

**Describe the results you received:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x153f973]

goroutine 1 [running]:
main.checkIfFileExists(0xc0001ec040, 0x1e, 0x2)
	cmd/podman/utils.go:74 +0x83
main.buildCmd(0x2bc5a80, 0x0, 0x0)
	cmd/podman/build.go:242 +0x178b
main.glob..func2(0x2b53fc0, 0xc0003668d0, 0x1, 0x1, 0x0, 0x0)
	cmd/podman/build.go:48 +0xde
github.com/spf13/cobra.(*Command).execute(0x2b53fc0, 0xc00003a0b0, 0x1, 0x1, 0x2b53fc0, 0xc00003a0b0)
	vendor/github.com/spf13/cobra/command.go:826 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x2b5d0c0, 0x0, 0x0, 0x40ea00)
	vendor/github.com/spf13/cobra/command.go:914 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0x2b5d0c0, 0x6, 0x192be95)
	vendor/github.com/spf13/cobra/command.go:864 +0x2b
main.main()
	cmd/podman/main.go:160 +0x63
```

**Describe the results you expected:**

An error message describing the correct usage of podman.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue also existed in buildah (https://github.com/containers/buildah/issues/1824) and was closed in containers/buildah@36dcedbabdd2a7312e84065dc0877389b2565a5e.

The segmentation fault happens in https://github.com/containers/libpod/blob/master/cmd/podman/utils.go#L74 when `IsDir()` is called but `file` is nil. Probably returning false when `err != nil` is sufficient to fix this.

**Output of `podman version`:**

```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.11.6
Git Commit:         9ba8dae0bfa5a5e894cf80e2ed114f6ca4bceb60
Built:              Wed Oct 30 19:46:46 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 9ba8dae0bfa5a5e894cf80e2ed114f6ca4bceb60
  go version: go1.11.6
  podman version: 1.6.3-dev
host:
  BuildahVersion: 1.11.4
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: unknown'
  Distribution:
    distribution: debian
    version: "10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 11759120384
  MemTotal: 25095081984
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: timon-debian
  kernel: 5.2.0-0.bpo.2-amd64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 6h 20m 24.56s (Approximately 0.25 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /home/timon/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 0.3
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  GraphRoot: /home/timon/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 102
  RunRoot: /run/user/1000
  VolumePath: /home/timon/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
@QiWang19 Could you fix this, also could you look at 
buildah bud file
Which does nothing, no crash but no error.
