### ISSUE TITLE
podman-compose up fails

### ISSUE THREAD

**Issue by Moshyfawn** [containers/libpod#4482]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
1. `podman network create server`
2. `podman run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --network="server" --name="nginx_proxy" jwilder/nginx-proxy`
3. `podman-compose -f docker-compose.dev.yml up -d`

**Describe the results you received:**
Console throws an error described below

**Describe the results you expected:**
App is built successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 695373824
  MemTotal: 8200818688
  OCIRuntime:
    name: crun
    package: crun-0.10.2-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.2
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8165212160
  SwapTotal: 8350855168
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: oleg-laptop
  kernel: 5.3.8-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 10h 38m 8.99s (Approximately 0.42 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 12
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

```
[root@oleg-laptop docker]# podman-compose -f docker-compose.dev.yml up -d
podman pod create --name=docker --share net -p 5434:5432
390baf908d932df598e3b2f28e270457aeb6548a2429045b442804c24e1e37de
0
podman volume inspect docker_database || podman volume create docker_database
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by sshnaidm** [comment]
`KeyError: 'mountPoint'` - in newer versions it's `Mountpoint`

**Comment by baude** [comment]
i dont think this applies here.  shouldnt this be filed with podman-compose?

**Comment by athrunsun** [comment]
This issue is also mentioned here: https://github.com/containers/podman-compose/issues/13#issuecomment-538183096, you might want to install devel version of podman-compose to resolve it for now.

**Comment by rhatdan** [comment]
This is a podman-compose issue, and should be handled there.
