### ISSUE TITLE
podman-compose error "pod already exists" after cold reboot

### ISSUE THREAD

**Issue by zonofthor** [containers/libpod#4536]
/kind bug

**Description**
Had been using podman-compose successfully for 1month when laptop froze and I had to cold reboot. After that no success initiating.

Exactly same configuration on desktop computer has no problems.

Have tried:
- full reinstall of podman & podman-compose
- `rm -Rf ~/.local/share/container`
- `podman rm -avf` (needed manual input b/c there was a "infra container". After this checked if any instance of pods, volumes or images => none 

**Steps to reproduce the issue:**

1. `podman-compose up` in directory having docker-compose.yml

**Describe the results you received:**
```Error: unable to create pod: error adding pod to state: name dev-database is in use: pod already exists
Traceback (most recent call last):
  File "/home/david/.local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/home/david/.local/lib/python3.7/site-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'
```

**Describe the results you expected:**
working services

**Additional information you deem important (e.g. issue happens only occasionally):**
no

**Output of `podman version`:**

```
podman pod create --name=dev-database --share net
125
podman volume inspect dev-database_mysql || podman volume create dev-database_mysql
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 9954676736
  MemTotal: 16520859648
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8342466560
  SwapTotal: 8342466560
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.3.11-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 20m 51.37s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/david/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7-1.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/david/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000
  VolumePath: /home/david/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Also notice

> podman volume ls
```
DRIVER   VOLUME NAME
local    dev-database_mysql
```

> podman volume prune
```
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Error: error freeing lock for volume dev-database_mysql: no such file or directory
```

**Comment by baude** [comment]
isnt this a podman-compose issue which is not part of this repo?

**Comment by zonofthor** [comment]
I honestly don't know... the errors come from the script yes but I'm guessing there's some locked entity in cache which libpod cannot modify.

**Comment by zonofthor** [comment]
Also notice

> podman volume ls
```
DRIVER   VOLUME NAME
local    dev-database_mysql
```

> podman volume prune
```
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Error: error freeing lock for volume dev-database_mysql: no such file or directory
```

**Comment by Michael-Jurek** [comment]
This is a **podman-compose** issue. I had the same problem. I fixed it with a newer version of podman-compose from devel branch of upstream project.
```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by zonofthor** [comment]
Can confirm that solves the error above!

Still some issues that weren't previously but I think config related.

**Comment by zonofthor** [comment]
Yes, definitely solved. THX!
