### ISSUE TITLE
Restore migrated container with container creation timeout

### ISSUE THREAD

**Issue by zhuguoliang** [containers/libpod#4779]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman run --tmpfs /run --security-opt=seccomp=unconfined -v /dira:/dirb sqldb /bin/bash /home/ubuntu/tmpscripts.sh

2. podman container checkpoint --tcp-established -l --export=/tmp/1.tar.gz

3. rsync -avzP --delete /dira/ root@hostb:/dira/    # this step ensures that dirs are in sync

4. scp /tmp1.tar.gz hostb:/tmp

5. podman container restore --tcp-established -i /tmp/1.tar.gz

**Describe the results you received:**

root@hostu18b:~# podman container restore --tcp-established -i /tmp/1.tar.gz
container init still running
ERRO[0260] Error removing container 04a8849a64faa5da42c144f46544a13fe17191adc36b0efd77be4ad68057a4a8 from runtime after creation failed
Error: failed to restore container 04a8849a64faa5da42c144f46544a13fe17191adc36b0efd77be4ad68057a4a8: container creation timeout: internal libpod error

**Describe the results you expected:**

successful restore

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0-rc1
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.7.0-rc1
host:
  BuildahVersion: 1.11.6
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.8, commit: d35534bc4b9bc722bf1ab6f4e828fcaa6bee236a-dirty'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 652050432
  MemTotal: 16273141760
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 993243136
  SwapTotal: 993243136
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: hostu18
  kernel: 4.15.0-66-generic
  os: linux
  rootless: false
  uptime: 24h 1m 8.46s (Approximately 1.00 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
ubuntu18
podman/unknown,now 1.7.0~0~dev1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
aliyun ecs

**Comment by adrianreber** [comment]
Can you run the restore with `--log-level debug`? I have not seen this error before. Not sure what is happening here.

**Comment by zhuguoliang** [comment]
Hi, the output is shared at https://gist.github.com/zhuguoliang/51bcd54093a42a1ae56d38cea178de9d

The cmd stuck at line: 
> INFO[0012] Running conmon under slice machine.slice and unitName libpod-conmon-04a8849a64faa5da42c144f46544a13fe17191adc36b0efd77be4ad68057a4a8.scope

for about 30s and then output final error

**Comment by adrianreber** [comment]
Are there any conmon messages in the journal? It would also be interesting to know how conmon calls runc. I usually try to use `execsnoop` from the bcc-tools to run it.

How I can try to reproduce this locally? Which container are you using? I see `sqldb` in `podman run`; is that container image available at any public registry?

**Comment by zhuguoliang** [comment]
I'll pack and upload to dockerhub, a moment pls

**Comment by zhuguoliang** [comment]
1. podman pull docker.io/elasticsearch:7.5.1
2. podman run  --security-opt=seccomp=unconfined  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" 2bd69c322e98
3. podman container checkpoint --tcp-established -l --export=/tmp/1.tar.gz
4.  scp /tmp/1.tar.gz root@hostb:/tmp/

on host B 
1. podman container restore --tcp-established -i /tmp/1.tar.gz

**Comment by adrianreber** [comment]
Thanks for the details. Running this with latest git I see an error, but not the one you described (timeout).

I get an error related to the file system changes. Something in the container changes `/usr/share/elasticsearch` from 755 to 775. CRIU sees this and aborts the restore because the file-system should be the same. This actually is a limitation I accepted because I am ignoring any directory mode changes. This could be fixed in Podman if necessary. A workaround for this is:

```
#️ cat Containerfile 
FROM docker.io/elasticsearch:7.5.1
RUN chmod 755 /usr/share/elasticsearch
#️ podman build .
STEP 1: FROM docker.io/elasticsearch:7.5.1
STEP 2: RUN chmod 755 /usr/share/elasticsearch
STEP 3: COMMIT
f052a22497f8ec1227064c4592d3c5e1580f4ad20805476577fa5ad281507833
f052a22497f8ec1227064c4592d3c5e1580f4ad20805476577fa5ad281507833
```

Using this image has the directory in the correct mode and now chekpointing and restore works:
```
# podman run -d --rm --security-opt=seccomp=unconfined  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node"  f052a22497f8ec
# podman container checkpoint  -l --export=/tmp/1.tar.gz
# podman container restore -i /tmp/1.tar.gz
```

The restore works and the container is running. Unfortunately the application in the container is not really happy as it seems to get confused by one of its lockfiles:
```
{"type": "server", "timestamp": "2020-01-08T10:05:19,899Z", "level": "DEBUG", "component": "o.e.a.a.c.n.s.TransportNodesStatsAction", "cluster.name": "docker-cluster", "node.name": "b0587c202c62", "message": "failed to execute on node [dgZvwhpLSUGzwYUJKopJmA]", "cluster.uuid": "jPAYwJb8QSGLFRSKAZgnog", "node.id": "dgZvwhpLSUGzwYUJKopJmA" , 
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [b0587c202c62][10.88.77.71:9300][cluster:monitor/nodes/stats[n]]",
"Caused by: org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2020-01-08T10:04:38Z, (lock=NativeFSLock(path=/usr/share/elasticsearch/data/nodes/0/node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2020-01-08T10:04:38.272378Z))",
"at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:191) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]",
"at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:1039) ~[elasticsearch-7.5.1.jar:7.5.1]",
```

During restore the lock file is re-created and probably gets another inode which might be the reason why the lockfile code breaks. This is, however, just me guessing. You probably need to talk to the developers of the software running in the container why this is happening.

From Podman's side everything works almost correct. The only real Podman bug here is that checkpointing does not correctly track the directory mode change from 755 to 775.

**Comment by zhuguoliang** [comment]
Thanks for your patience but It seems that I cannot reproduce it in my dev env.

I rebuild the images with podman build the containerfile above,
I took the following steps:
1. podman save -o a.tar 93afe57d19e4
2. scp a.tar hostb:/tmp
3. podman load -i /tmp/a.tar
4.  podman container restore --log-level debug --tcp-established -i /tmp/3.tar.gz 
(Note that 3.tar.gz is the checkpoint file)

The log is attached in the following link.
https://gist.github.com/zhuguoliang/214f7875f98e0491c834b23c7e31c55c

**Comment by superligen** [comment]
https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/store/NativeFSLockFactory.java

“FileTime ctime = Files.readAttributes(path, BasicFileAttributes.class).creationTime(); 
      if (!creationTime.equals(ctime)) {
        throw new AlreadyClosedException("Underlying file changed by an external force at " + ctime + ", (lock=" + this + ")");
      }”

looks like the locker file creation time is not restored correctly, and make this lock vaild method failed.

**Comment by adrianreber** [comment]
> looks like the locker file creation time is not restored correctly, and make this lock vaild method failed.

Thanks for looking into this. On my system the file creation time is correct and the same as before
checkpointing. The file date is the same as the container initial creation time. I am wondering how is 
`creationTime` created. Where does `creationTime` come from. Is that maybe confused, that the process was not running for some time. Maybe lucene cannot handle that the time of the system changed, but the process was not running. Maybe this also needs a time namespace.

My main question is how is the value of `creationTime` created? I am pretty sure the ctime of the lock file is correct.

**Comment by adrianreber** [comment]
@zhuguoliang I do not see the timeout you are still seeing. One big difference on my test VM is, that I do not have an IPv6 address. Container checkpoint and restore only looks at the IPv4 address right now, so maybe the problem you are seeing is somehow IPv6 related. Maybe you can somehow try to create a container without IPv6 addresses. At least to verify if that is the problem.

**Comment by adrianreber** [comment]
@superligen I had a look at the lucene code and a closer look at the error message, the problem seems to be that the creation time is only restored with seconds as precision. Looking at the output of `stat` I can see the file time as `10:04:38.000000000` the original time of the file, before checkpoint and restore was `10:04:38.272378` and this is also part of the error message:
`changed by an external force at 2020-01-08T10:04:38Z` and `creationTime=2020-01-08T10:04:38.272378Z`.

This seems to be a limitation of tar and timestamps, because the files are migrated using tar.

If I put the lock file outside of the container it works:
```
# mkdir /tmp/data
# chown 1000:1000 data
# podman run -d --rm -v /tmp/data:/usr/share/elasticsearch/data:Z --security-opt=seccomp=unconfined  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node"  f052a22497f8ec
# podman container checkpoint  -l --export=/tmp/1.tar.gz
# podman container restore -i /tmp/1.tar.gz
```
For the migration transferring /tmp/data via rsync should restore the lock file with the correct timestamp (up to the nano second (I hope)).

This still does not solve the problems @zhuguoliang is seeing, but I cannot reproduce those errors locally.

@superligen Maybe opening a ticket at upstream lucene to only check the timestamp of the lockfile up to the second and ignore the nano-seconds. Not sure if they will like this however. It would make migrating much easier.

**Comment by zhuguoliang** [comment]
@adrianreber Hi Mr.Reber, I kept on seeing timeout when restoring containers. The logs says that I am stuck at running conmon.

```
root@hostb:~# podman container restore  --log-level debug    -i /tmp/3.tar.gz
DEBU[0000] Reading configuration file "/usr/share/containers/libpod.conf"
DEBU[0000] Merged system config "/usr/share/containers/libpod.conf": &{{false false false false false true} 0 {   [] [] []}  docker://  runc map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata-fc:[/usr/bin/kata-fc] kata-qemu:[/usr/bin/kata-qemu] kata-runtime:[/usr/bin/kata-runtime] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] [crun runc] [crun] [] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] systemd   /var/run/libpod -1 false /etc/cni/net.d/ [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman []   k8s.gcr.io/pause:3.1 /pause false false  2048 shm    false false}
DEBU[0000] Using conmon: "/usr/libexec/podman/conmon"
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver
DEBU[0000] Using graph root /var/lib/containers/storage
DEBU[0000] Using run root /var/run/containers/storage
DEBU[0000] Using static dir /var/lib/containers/storage/libpod
DEBU[0000] Using tmp dir /var/run/libpod
DEBU[0000] Using volume path /var/lib/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] cached value indicated that overlay is supported
DEBU[0000] cached value indicated that metacopy is not being used
DEBU[0000] cached value indicated that native-diff is usable
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
INFO[0000] [graphdriver] using prior storage driver: overlay
DEBU[0000] Initializing event backend journald
WARN[0000] Error initializing configured OCI runtime kata-qemu: no valid executable found for OCI runtime kata-qemu: invalid argument
WARN[0000] Error initializing configured OCI runtime kata-fc: no valid executable found for OCI runtime kata-fc: invalid argument
DEBU[0000] using runtime "/usr/sbin/runc"
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
WARN[0000] Error initializing configured OCI runtime kata-runtime: no valid executable found for OCI runtime kata-runtime: invalid argument
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist
WARN[0000] Error loading CNI config file /etc/cni/net.d/99-loopback.conf: error parsing configuration: missing 'type'
WARN[0000] Default CNI network name podman is unchangeable
DEBU[0003] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]@93afe57d19e4a696a27214babc247b2a71486beea485d8f53f3b0b48a09c0e9f"
DEBU[0003] Allocated lock 5 for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
DEBU[0003] Setting CGroups for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 to machine.slice:libpod:0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
DEBU[0003] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]@93afe57d19e4a696a27214babc247b2a71486beea485d8f53f3b0b48a09c0e9f"
DEBU[0003] exporting opaque data as blob "sha256:93afe57d19e4a696a27214babc247b2a71486beea485d8f53f3b0b48a09c0e9f"
DEBU[0003] created container "0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8"
DEBU[0003] container "0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8" has work directory "/var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata"
DEBU[0003] container "0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8" has run directory "/var/run/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata"
DEBU[0003] Trying to restore container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
DEBU[0007] Created OCI spec for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 at /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/config.json
DEBU[0007] Made network namespace at /var/run/netns/cni-7c235053-a15f-cfcc-a2ee-bf4b8a48bc54 for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
INFO[0007] About to add CNI network lo (type=loopback)
DEBU[0007] overlay: mount_data=lowerdir=/var/lib/containers/storage/overlay/l/4BACK6HMQIMCPTCVW3XJJAUYM2:/var/lib/containers/storage/overlay/l/KP6MGBEI2HTO6C3AYMFKGILS3N:/var/lib/containers/storage/overlay/l/RCWO4YCPOL5KTHYDTILG66Q2ZI:/var/lib/containers/storage/overlay/l/UTAQE5Q7E2KARV2UGKP2DMJEUT:/var/lib/containers/storage/overlay/l/JKE2UWQTMVCAYET55O4LOT2QXS:/var/lib/containers/storage/overlay/l/YTD33BGFLV6Y3FBXO3NUOWPGYU:/var/lib/containers/storage/overlay/l/626AG7DCXZ6PQHA3T5ROY2T4N7:/var/lib/containers/storage/overlay/l/GX6FJFSRA7JFLUNHH5ZVPQS3N3,upperdir=/var/lib/containers/storage/overlay/90d1382f9129d1045f3ffa4d8d3d48c6083ece5d69017e3640839072eca56add/diff,workdir=/var/lib/containers/storage/overlay/90d1382f9129d1045f3ffa4d8d3d48c6083ece5d69017e3640839072eca56add/work
DEBU[0007] mounted container "0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8" at "/var/lib/containers/storage/overlay/90d1382f9129d1045f3ffa4d8d3d48c6083ece5d69017e3640839072eca56add/merged"
DEBU[0007] Created root filesystem for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 at /var/lib/containers/storage/overlay/90d1382f9129d1045f3ffa4d8d3d48c6083ece5d69017e3640839072eca56add/merged
INFO[0007] Got pod network &{Name:pensive_chatterjee Namespace:pensive_chatterjee ID:0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 NetNS:/var/run/netns/cni-7c235053-a15f-cfcc-a2ee-bf4b8a48bc54 Networks:[{Name:podman Ifname:}] RuntimeConfig:map[podman:{IP:10.88.0.23 MAC:56:26:0c:57:6c:ac PortMappings:[{HostPort:9200 ContainerPort:9200 Protocol:tcp HostIP:} {HostPort:9300 ContainerPort:9300 Protocol:tcp HostIP:}] Bandwidth:<nil> IpRanges:[]}]}
INFO[0007] About to add CNI network podman (type=bridge)
DEBU[0008] [0] CNI result: Interfaces:[{Name:cni-podman0 Mac:8a:2c:20:7e:4d:a1 Sandbox:} {Name:veth90ad59ef Mac:9e:f8:5f:eb:9a:c5 Sandbox:} {Name:eth0 Mac:56:26:0c:57:6c:ac Sandbox:/var/run/netns/cni-7c235053-a15f-cfcc-a2ee-bf4b8a48bc54}], IP:[{Version:4 Interface:0xc000427278 Address:{IP:10.88.0.23 Mask:ffff0000} Gateway:10.88.0.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:<nil>}], DNS:{Nameservers:[] Domain: Search:[] Options:[]}
DEBU[0008] generate.NewFromFile at /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/config.json
INFO[0008] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]
INFO[0008] IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]
DEBU[0008] /etc/system-fips does not exist on host, not mounting FIPS mode secret
DEBU[0008] Created OCI spec for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 at /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/config.json
DEBU[0008] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]localhost/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8:latest"
DEBU[0008] reference "[overlay@/var/lib/containers/storage+/var/run/containers/storage]localhost/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8:latest" does not resolve to an image ID
DEBU[0008] Applying tar in /var/lib/containers/storage/overlay/90d1382f9129d1045f3ffa4d8d3d48c6083ece5d69017e3640839072eca56add/diff
DEBU[0008] /usr/libexec/podman/conmon messages will be logged to syslog
DEBU[0008] running conmon: /usr/libexec/podman/conmon    args="[--api-version 1 -s -c 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 -u 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 -r /usr/sbin/runc -b /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata -p /var/run/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/pidfile -l k8s-file:/var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level debug --syslog --conmon-pidfile /var/run/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/conmon.pid --exit-command /usr/local/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containers/storage --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 --restore /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/checkpoint]"
INFO[0008] Running conmon under slice machine.slice and unitName libpod-conmon-0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8.scope
DEBU[0249] Cleaning up container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
DEBU[0249] Tearing down network namespace at /var/run/netns/cni-7c235053-a15f-cfcc-a2ee-bf4b8a48bc54 for container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8
INFO[0249] About to del CNI network lo (type=loopback)
INFO[0249] Got pod network &{Name:pensive_chatterjee Namespace:pensive_chatterjee ID:0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 NetNS:/var/run/netns/cni-7c235053-a15f-cfcc-a2ee-bf4b8a48bc54 Networks:[{Name:podman Ifname:eth0}] RuntimeConfig:map[podman:{IP: MAC: PortMappings:[{HostPort:9200 ContainerPort:9200 Protocol:tcp HostIP:} {HostPort:9300 ContainerPort:9300 Protocol:tcp HostIP:}] Bandwidth:<nil> IpRanges:[]}]}
INFO[0249] About to del CNI network podman (type=bridge)
DEBU[0249] container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8 failed to unmount /var/lib/containers/storage/overlay-containers/0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8/userdata/shm : invalid argument
DEBU[0249] unmounted container "0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8"
ERRO[0249] failed to restore container 0028b68f9a8959c6f6fd92f03f63104f9e649b777a77eb549b4f84fe1d0a90e8: container creation timeout: internal libpod error


```

**Comment by zhuguoliang** [comment]
@adrianreber I'll leave this issue open and ask about the timeout in a new issue.

**Comment by zhuguoliang** [comment]
@adrianreber Hi, is there any steps to diasble ipv6 for podman? I ensured that the following is in my "/etc/sysctl.conf" of ubuntu18
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 =1
```

**Comment by zhuguoliang** [comment]
@adrianreber after disable ipv6 the timeout problem is gone, case closed.

 The lucene problem stems from libpod tar format, will look into it later.
