### ISSUE TITLE
Panic panic: d.nx != 0 on push

### ISSUE THREAD

**Issue by tylarb** [containers/libpod#5955]
/kind bug

**Description**

On push, get `panic: d.nx != 0` in crypto/sha256.(*digest).checkSum

**Steps to reproduce the issue:**

1. Login to GCR

2. Push image which built locally successfully

**Describe the results you received:**

I've got a full panic message, and core dump as well. What's the best way to provide these?

```
gcloud auth print-access-token | podman login -u oauth2accesstoken --password-stdin https://gcr.io
Login Succeeded!
podman push gcr.io/[redacted]
Getting image source signatures
Copying blob f1c9a075de3f done
Copying blob b3c09275c51c done
Copying blob fd4af127415b [>-------------------------------------] 2.4MiB / 83.8MiB
Copying blob 5b188fe045a4 done
Copying blob 24111d20d75e [--------------------------------------] 1.0MiB / 252.2MiB
Copying blob b05580fca2f9 [--------------------------------------] 8.0b / 200.5MiB
panic: d.nx != 0

goroutine 70 [running]:
panic(0x55eecc2dcc80, 0x55eecc5df010)
        /usr/lib/golang/src/runtime/panic.go:565 +0x2c9 fp=0xc0007d2a80 sp=0xc0007d29f0 pc=0x55eeca58d569
crypto/sha256.(*digest).checkSum(0xc0007d2ba0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/sha256/sha256.go:262 +0x1f1 fp=0xc0007d2b30 sp=0xc0007d2a80 pc=0x55eeca7a5b61
crypto/sha256.(*digest).Sum(0xc0001f9280, 0x0, 0x0, 0x0, 0xc0007d2cc8, 0x7c3a4dcb, 0x8facf8e95a615ccc)
        /usr/lib/golang/src/crypto/sha256/sha256.go:238 +0x7a fp=0xc0007d2c30 sp=0xc0007d2b30 pc=0x55eeca7a577a
github.com/containers/libpod/vendor/github.com/opencontainers/go-digest.NewDigest(0x55eecb924b83, 0x6, 0x55eecc649d20, 0xc0001f9280, 0x18, 0xc0007d2cc0)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/opencontainers/go-digest/digest.go:40 +0x48 fp=0xc0007d2c78 sp=0xc0007d2c30 pc=0x55eeca7b8ca8
github.com/containers/libpod/vendor/github.com/opencontainers/go-digest.(*digester).Digest(0xc00058cf40, 0x55eecc62cdf8, 0xc0002af020)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/opencontainers/go-digest/digester.go:38 +0x4b fp=0xc0007d2cb8 sp=0xc0007d2c78 pc=0x55eeca7b958b
github.com/containers/libpod/vendor/github.com/containers/image/v5/docker.(*dockerImageDestination).PutBlob(0xc0003de780, 0x55eecc645b60, 0xc0000c0028, 0x55eecc60aa60, 0xc0000c2020, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/docker/docker_image_dest.go:172 +0x696 fp=0xc0007d3290 sp=0xc0007d2cb8 pc=0x55eecacd57b6
github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.(*copier).copyBlobFromStream(0xc000304d80, 0x55eecc645b60, 0xc0000c0028, 0x7eff012d83f0, 0xc000632bc0, 0xc000362fa0, 0x47, 0xc877600, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:1331 +0x578 fp=0xc0007d3828 sp=0xc0007d3290 pc=0x55eecb1abf98
github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.(*imageCopier).copyLayerFromStream(0xc00036c840, 0x55eecc645b60, 0xc0000c0028, 0x7eff012d83f0, 0xc000632bc0, 0xc000362fa0, 0x47, 0xc877600, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:1131 +0x1cb fp=0xc0007d39f8 sp=0xc0007d3828 pc=0x55eecb1ab32b
github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc00036c840, 0x55eecc645b60, 0xc0000c0028, 0xc000362fa0, 0x47, 0xc877600, 0x0, 0x0, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:1073 +0x35f fp=0xc0007d3d68 sp=0xc0007d39f8 pc=0x55eecb1aa78f
github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x0, 0xc000362fa0, 0x47, 0xc877600, 0x0, 0x0, 0x0, 0x0, 0xc0004618c0, 0x26, ...)
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:828 +0x416 fp=0xc0007d3f68 sp=0xc0007d3d68 pc=0x55eecb1b0d86
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0007d3f70 sp=0xc0007d3f68 pc=0x55eeca5bb5d1
created by github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2
        /home/abuild/rpmbuild/BUILD/libpod-1.9.0/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:860 +0x207
```

**Describe the results you expected:**
No panic

**Additional information you deem important (e.g. issue happens only occasionally):**

Happened a single time - next push failed with 
```
Error: Error copying image to the remote destination: Error writing blob: Error determining upload URL: http: no Location header in response
```

But that could be problem with infrastructure - pushes from outside of GCP work fine, same podman version

**Output of `podman version`:**

```
podman --version
podman version 1.9.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.12.12
  podmanVersion: 1.9.0
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.6-1.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 2721f230f94894671f141762bd0d1af2fb263239'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: behave
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  memFree: 10750115840
  memTotal: 15589875712
  ociRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.2-3.git21fdece.module_el8.1.0+298+41f9343a.x86_64
    version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  swapFree: 0
  swapTotal: 0
  uptime: 48h 7m 40.19s (Approximately 2.00 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  configFile: /home/tramer/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module_el8.1.0+298+41f9343a.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/tramer/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 21
  runRoot: /run/user/1000
  volumePath: /home/tramer/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[tramer@behave ~]$ rpm -q podman
podman-1.9.0-4.1.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 8 on GCP, podman from development repo.

**Comment by mheon** [comment]
@mtrmac Looks like this is coming out of c/image's copy code?

**Comment by mheon** [comment]
Though it's going into the digest code, and deep enough that I'm really curious as to how it got there. It's not a segfault, and SHA256 should otherwise be pretty straightforward?

**Comment by tylarb** [comment]
I had previously been running podman 1.6.4 and then updated to 1.9.0 just before this panic occurred. Images had been built and pushed using podman 1.6.4 successfully.

**Comment by mtrmac** [comment]
This is https://github.com/containers/image/issues/750 , see https://github.com/containers/image/issues/750#issuecomment-603953702 .

Avoiding the panic in common cases is trivial, handling the corner cases is more tricky WRT concurrency.

**Comment by rhatdan** [comment]
This should now be fixed in master branch, as far as I can see.  Reopen if I am mistaken.
