### ISSUE TITLE
[unit test] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chuanchang** [containers/libpod#6164]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. make localunit

**Describe the results you received:**
```
=== RUN   TestCreateNewSHMBadSizeRoundsUp
    TestCreateNewSHMBadSizeRoundsUp: shm_lock_test.go:78:
                Error Trace:    shm_lock_test.go:78
                Error:          Received unexpected error:
                                file exists
                                failed to create 7 locks in /test1
                                github.com/containers/libpod/libpod/lock/shm.CreateSHMLock
                                        /home/fedora/go/src/github.com/containers/libpod/libpod/lock/shm/shm_lock.go:54
                                github.com/containers/libpod/libpod/lock/shm.TestCreateNewSHMBadSizeRoundsUp
                                        /home/fedora/go/src/github.com/containers/libpod/libpod/lock/shm/shm_lock_test.go:77
                                testing.tRunner
                                        /usr/lib/golang/src/testing/testing.go:991
                                runtime.goexit
                                        /usr/lib/golang/src/runtime/asm_amd64.s:1373
                Test:           TestCreateNewSHMBadSizeRoundsUp
--- FAIL: TestCreateNewSHMBadSizeRoundsUp (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6a38a3]

goroutine 19 [running]:
testing.tRunner.func1.1(0x6ea700, 0x973c20)
        /usr/lib/golang/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0000ce480)
        /usr/lib/golang/src/testing/testing.go:943 +0x3f9
panic(0x6ea700, 0x973c20)
        /usr/lib/golang/src/runtime/panic.go:969 +0x166
github.com/containers/libpod/libpod/lock/shm.(*SHMLocks).GetMaxLocks(...)
        /home/fedora/go/src/github.com/containers/libpod/libpod/lock/shm/shm_lock.go:95
github.com/containers/libpod/libpod/lock/shm.TestCreateNewSHMBadSizeRoundsUp(0xc0000ce480)
        /home/fedora/go/src/github.com/containers/libpod/libpod/lock/shm/shm_lock_test.go:80 +0xa3
testing.tRunner(0xc0000ce480, 0x75bdf0)
        /usr/lib/golang/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/lib/golang/src/testing/testing.go:1042 +0x357

Ginkgo ran 5 suites in 16.575443792s
Test Suite Failed
make: *** [Makefile:293: localunit] Error 1
```

**Describe the results you expected:**
fix it

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.14.2
Git Commit:         18b273b72ba76d485eb1b4d5df48bff1685953ff
Built:              Mon May 11 08:41:52 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: fedora31
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-300.fc32.x86_64
  memFree: 2892550144
  memTotal: 4118323200
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 44m 22.33s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/fedora/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/fedora/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/fedora/.local/share/containers/storage/volumes
version:
  Built: 1589186512
  GitCommit: 18b273b72ba76d485eb1b4d5df48bff1685953ff
  GoVersion: go1.14.2
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[fedora@fedora32 libpod]$ git rev-parse HEAD
18b273b72ba76d485eb1b4d5df48bff1685953ff
```
```
$ cat /etc/redhat-release
Fedora release 32 (Thirty Two)

$ rpm -q crun
crun-0.13-2.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack

**Comment by vrothberg** [comment]
While it's unclear to me why the test continues facing an unexpected error, I opened https://github.com/containers/libpod/pull/6169 to add an extra nil check.
