### ISSUE TITLE
Podman crashes while loading OCI image from BuildStream

### ISSUE THREAD

**Issue by gasinvein** [containers/libpod#6361]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

An OCI image created by BuildStream (namely `freedesktop-sdk`) casuses Podman to crash while trying to import it. No matter if it's a tarball or a plain directory.

**Steps to reproduce the issue:**

1. Build [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) with [buildstream](https://gitlab.com/BuildStream/buildstream) and export OCI image, e.g.
    1. `bst build -- oci/flatpak-oci.bst`
    2. `bst checkout -- oci/flatpak-oci.bst path/to/checkout/freedesktop-sdk-oci`

2. Try to import created image with podman:
    1. `cd path/to/checkout`
    2. `podman pull oci:freedesktop-sdk-oci`

   Also a tarball can be created from directory, then loaded via `podman load -i freedesktop-sdk-oci.tar`, with the same result.

**Describe the results you received:**

Podman crashes, short log:
```
Getting image source signatures
Copying blob f78672e1807d skipped: already exists  
Copying blob e385484c99c6 skipped: already exists  
Copying blob 878a38929d6c skipped: already exists  
Copying config 1cb772b8a8 done  
Writing manifest to image destination
Storing signatures
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x556cbe52009b]
```

<details>
<summary>
Full log
</summary>

```
Getting image source signatures
Copying blob f78672e1807d skipped: already exists  
Copying blob e385484c99c6 skipped: already exists  
Copying blob 878a38929d6c skipped: already exists  
Copying config 1cb772b8a8 done  
Writing manifest to image destination
Storing signatures
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x556cbe52009b]

goroutine 1 [running]:
panic(0x556cbf70ee40, 0x556cc09a45c0)
	/usr/lib/golang/src/runtime/panic.go:1064 +0x471 fp=0xc00059e3b0 sp=0xc00059e2f8 pc=0x556cbdf71191
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:212
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:695 +0x3de fp=0xc00059e3e0 sp=0xc00059e3b0 pc=0x556cbdf8830e
github.com/containers/libpod/vendor/github.com/containers/image/v5/manifest.(*OCI1).Inspect(0xc00078c100, 0xc00010e370, 0x40, 0xc00038e500, 0x0)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/manifest/oci.go:245 +0x38b fp=0xc00059e568 sp=0xc00059e3e0 pc=0x556cbe52009b
github.com/containers/libpod/vendor/github.com/containers/image/v5/storage.(*storageImageDestination).Commit(0xc0003841e0, 0x556cbf9d6560, 0xc0000460c8, 0x556cbf9c6220, 0xc0000904e0, 0x0, 0x0)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/storage/storage_image.go:753 +0x3d0 fp=0xc00059f120 sp=0xc00059e568 pc=0x556cbe57ef40
github.com/containers/libpod/vendor/github.com/containers/image/v5/copy.Image(0x556cbf9d6560, 0xc0000460c8, 0xc0002060e0, 0x556cbf9e5a20, 0xc000319ec0, 0x556cbf9e5f00, 0xc00003d0b0, 0xc0002d7440, 0xc00071ab00, 0x34a, ...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/v5/copy/copy.go:328 +0x81c fp=0xc00059f4b8 sp=0xc00059f120 pc=0x556cbeafe57c
github.com/containers/libpod/libpod/image.(*Runtime).doPullImage(0xc0002bc730, 0x556cbf9d6560, 0xc0000460c8, 0xc000016700, 0xc0003885a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/libpod/image/pull.go:314 +0x389 fp=0xc00059f6f0 sp=0xc00059f4b8 pc=0x556cbedafb79
github.com/containers/libpod/libpod/image.(*Runtime).pullImageFromHeuristicSource(0xc0002bc730, 0x556cbf9d6560, 0xc0000460c8, 0x7fff9d9d5aea, 0x1b, 0x556cbf99d2e0, 0xc000010020, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/libpod/image/pull.go:250 +0x3f9 fp=0xc00059f850 sp=0xc00059f6f0 pc=0x556cbedaed79
github.com/containers/libpod/libpod/image.(*Runtime).New(0xc0002bc730, 0x556cbf9d6560, 0xc0000460c8, 0x7fff9d9d5aea, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x556cbf99d2e0, ...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/libpod/image/image.go:160 +0x21f fp=0xc00059f950 sp=0xc00059f850 pc=0x556cbed9e40f
github.com/containers/libpod/pkg/adapter.(*LocalRuntime).New(0xc00007d360, 0x556cbf9d6560, 0xc0000460c8, 0x7fff9d9d5aea, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x556cbf99d2e0, ...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/pkg/adapter/runtime.go:160 +0x11e fp=0xc00059fa08 sp=0xc00059f950 pc=0x556cbf0bba8e
main.pullCmd(0x556cc0a4d920, 0x0, 0x0)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/cmd/podman/pull.go:148 +0x448 fp=0xc00059fd68 sp=0xc00059fa08 pc=0x556cbf20b468
main.glob..func59(0x556cc09c20c0, 0xc00035a180, 0x1, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/cmd/podman/pull.go:37 +0x88 fp=0xc00059fd90 sp=0xc00059fd68 pc=0x556cbf232108
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x556cc09c20c0, 0xc00003c1a0, 0x1, 0x1, 0x556cc09c20c0, 0xc00003c1a0)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:838 +0x455 fp=0xc00059fe68 sp=0xc00059fd90 pc=0x556cbe361545
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x556cc09c7a00, 0x6, 0x556cbf24b609, 0x8)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:943 +0x319 fp=0xc00059ff40 sp=0xc00059fe68 pc=0x556cbe362049
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:883
main.main()
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/cmd/podman/main.go:169 +0xb2 fp=0xc00059ff88 sp=0xc00059ff40 pc=0x556cbf1f5872
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21a fp=0xc00059ffe0 sp=0xc00059ff88 pc=0x556cbdf73c2a
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00059ffe8 sp=0xc00059ffe0 pc=0x556cbdfa2b21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x556cbf972218, 0x556cc0a3d080, 0x1411, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000066fb0 sp=0xc000066f90 pc=0x556cbdf74026
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc000066fe0 sp=0xc000066fb0 pc=0x556cbdf73ecb
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x556cbdfa2b21
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:242 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x556cbf972218, 0x556cc0a3f4a0, 0x140c, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0000677a8 sp=0xc000067788 pc=0x556cbdf74026
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.bgsweep(0xc00007e000)
	/usr/lib/golang/src/runtime/mgcsweep.go:89 +0x135 fp=0xc0000677d8 sp=0xc0000677a8 pc=0x556cbdf605b5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000677e0 sp=0xc0000677d8 pc=0x556cbdfa2b21
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:214 +0x5e

goroutine 4 [sleep]:
runtime.gopark(0x556cbf972218, 0x556cc0a3f460, 0x1313, 0x2)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000067f28 sp=0xc000067f08 pc=0x556cbdf74026
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.scavengeSleep(0x233349, 0xd9652)
	/usr/lib/golang/src/runtime/mgcscavenge.go:214 +0xc1 fp=0xc000067f78 sp=0xc000067f28 pc=0x556cbdf5ea11
runtime.bgscavenge(0xc00007e000)
	/usr/lib/golang/src/runtime/mgcscavenge.go:315 +0x189 fp=0xc000067fd8 sp=0xc000067f78 pc=0x556cbdf5ebc9
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000067fe0 sp=0xc000067fd8 pc=0x556cbdfa2b21
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:215 +0x80

goroutine 5 [finalizer wait]:
runtime.gopark(0x556cbf972218, 0x556cc0a7a1a0, 0x61410, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000066758 sp=0xc000066738 pc=0x556cbdf74026
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:175 +0xa7 fp=0xc0000667e0 sp=0xc000066758 pc=0x556cbdf560e7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x556cbdfa2b21
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:156 +0x63

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000521dc0, 0x556cbdf41418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000068760 sp=0xc000068740 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc000053000)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0000687d8 sp=0xc000068760 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000687e0 sp=0xc0000687d8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000521da0, 0x556cbdf41418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000068f60 sp=0xc000068f40 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc00004e000)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc000068fd8 sp=0xc000068f60 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000068fe0 sp=0xc000068fd8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000208540, 0x556cbdf41418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000062760 sp=0xc000062740 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc00005a800)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0000627d8 sp=0xc000062760 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000627e0 sp=0xc0000627d8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 54 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000521db0, 0x556cbdf41418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00023cf60 sp=0xc00023cf40 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc000050800)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc00023cfd8 sp=0xc00023cf60 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00023cfe0 sp=0xc00023cfd8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000521dd0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000238760 sp=0xc000238740 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc000055800)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0002387d8 sp=0xc000238760 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002387e0 sp=0xc0002387d8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 41 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc0001b8210, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000238f60 sp=0xc000238f40 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc000058000)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc000238fd8 sp=0xc000238f60 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000238fe0 sp=0xc000238fd8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 42 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000208550, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000239760 sp=0xc000239740 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc00005d000)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0002397d8 sp=0xc000239760 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002397e0 sp=0xc0002397d8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x556cbf9720a0, 0xc000208560, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000069760 sp=0xc000069740 pc=0x556cbdf74026
runtime.gcBgMarkWorker(0xc00005f800)
	/usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0000697d8 sp=0xc000069760 pc=0x556cbdf59ae5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000697e0 sp=0xc0000697d8 pc=0x556cbdfa2b21
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1821 +0x79

goroutine 21 [chan receive]:
runtime.gopark(0x556cbf972018, 0xc000211d38, 0x170e, 0x2)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000069ed0 sp=0xc000069eb0 pc=0x556cbdf74026
runtime.chanrecv(0xc000211ce0, 0xc000069fb0, 0xc00015a001, 0xc000211ce0)
	/usr/lib/golang/src/runtime/chan.go:525 +0x2eb fp=0xc000069f60 sp=0xc000069ed0 pc=0x556cbdf4339b
runtime.chanrecv2(0xc000211ce0, 0xc000069fb0, 0x556cbe61af1b)
	/usr/lib/golang/src/runtime/chan.go:412 +0x2b fp=0xc000069f90 sp=0xc000069f60 pc=0x556cbdf4309b
github.com/containers/libpod/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x556cc0a40e20)
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:1010 +0x8d fp=0xc000069fd8 sp=0xc000069f90 pc=0x556cbe7c55cd
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000069fe0 sp=0xc000069fd8 pc=0x556cbdfa2b21
created by github.com/containers/libpod/vendor/k8s.io/klog.init.0
	/builddir/build/BUILD/libpod-1.9.2/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:411 +0xd8
fish: 'podman pull oci:freedesktop-sdk…' terminated by signal SIGABRT (Abort)
```

</details>

**Describe the results you expected:**

Podman loads the image and it's available locally.

**Output of `podman version`:**

```
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

<details>
<summary>
Here it is
</summary>

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.2
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.16-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.16, commit: 1044176f7dd177c100779d1c63931d6022e419bd'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: carbide
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.12-300.fc32.x86_64
  memFree: 2873425920
  memTotal: 16468992000
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 7162032128
  swapTotal: 8234463232
  uptime: 12h 19m 57.24s (Approximately 0.50 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/gasinvein/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/gasinvein/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/gasinvein/.local/share/containers/storage/volumes
```
</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.2-1.fc32.x86_64
```

This also happens with Podman from Fedora Rawhide (`2.0.0-0.62.dev.gitc8d6426`, rebuilt for Fedora 32), with slightly different (and shorter) output.

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
This should be fixed by https://github.com/containers/image/pull/940 ; testing would be appreciated.
