### ISSUE TITLE
podman-remote: images: panic

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#6623]
Start podman server:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ ~/src/atomic/2018-02.podman/libpod/bin/podman system service --timeout=0 $MYSOCK
```
In separate shell:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ ./bin/podman-remote --url $MYSOCK images
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/containers/libpod/pkg/domain/infra/tunnel.(*ImageEngine).List(0xc000116010, 0x17baa40, 0xc000225ce0, 0xc00019b500, 0x224fbb8, 0x0, 0x0, 0xc000547c78, 0xd027d7, 0xc0006bcd00, ...)
        pkg/domain/infra/tunnel/images.go:48 +0x381
github.com/containers/libpod/cmd/podman/images.images(0x219c140, 0x224fbb8, 0x0, 0x0, 0x0, 0x0)
        cmd/podman/images/list.go:96 +0x110
github.com/spf13/cobra.(*Command).execute(0x219c140, 0xc00003c0d0, 0x0, 0x0, 0x219c140, 0xc00003c0d0)
        vendor/github.com/spf13/cobra/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x21a8620, 0xc000042198, 0x1399c00, 0x224fbb8)
        vendor/github.com/spf13/cobra/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:883
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        vendor/github.com/spf13/cobra/command.go:876
main.Execute()
        cmd/podman/root.go:89 +0xec
main.main()
        cmd/podman/main.go:57 +0x168
```
Happens if there are one or more images only; does not happen if there are zero.

`podman images` (non-remote) works fine.

master @ e0dd2279120f9883c0678cce644952007e3ae771

**Comment by edsantiago** [comment]
root and rootless
