### ISSUE TITLE
Running "podman Containerfile" without the -f flag  runs into panic and segmentation fault (Fuzz testing :) 

### ISSUE THREAD

**Issue by zvonkok** [containers/libpod#6825]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running "podman Containerfile" without the -f flag  runs into panic and segmentation fault

**Steps to reproduce the issue:**

1. cd /tmp && touch Containerfile

2. podman build Containerfile

**Describe the results you received:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55795b2d1eaa]

goroutine 1 [running]:
panic(0x55795bc33980, 0x55795cdb61a0)
	/usr/lib/golang/src/runtime/panic.go:722 +0x2c6 fp=0xc0001e1340 sp=0xc0001e12b0 pc=0x55795a157106
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:199
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:394 +0x3f0 fp=0xc0001e1370 sp=0xc0001e1340 pc=0x55795a16ce70
main.checkIfFileExists(0xc0001ed2a0, 0x1d, 0x2)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/cmd/podman/utils.go:74 +0x9a fp=0xc0001e13c0 sp=0xc0001e1370 pc=0x55795b2d1eaa
main.buildCmd(0x55795ce53280, 0x0, 0x0)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/cmd/podman/build.go:242 +0x1696 fp=0xc0001e1d40 sp=0xc0001e13c0 pc=0x55795b281c26
main.glob..func2(0x55795cdc86c0, 0xc0003feb10, 0x1, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/cmd/podman/build.go:48 +0xe0 fp=0xc0001e1d68 sp=0xc0001e1d40 pc=0x55795b2d7a00
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x55795cdc86c0, 0xc0000ae170, 0x1, 0x1, 0x55795cdc86c0, 0xc0000ae170)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:826 +0x462 fp=0xc0001e1e40 sp=0xc0001e1d68 pc=0x55795a322ba2
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x55795cdd67c0, 0x6, 0x55795b2f6e83, 0x8)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:914 +0x2fd fp=0xc0001e1f18 sp=0xc0001e1e40 pc=0x55795a3235fd
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/cmd/podman/main.go:160 +0xb2 fp=0xc0001e1f60 sp=0xc0001e1f18 pc=0x55795b29f8c2
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc0001e1fe0 sp=0xc0001e1f60 pc=0x55795a158e76
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001e1fe8 sp=0xc0001e1fe0 pc=0x55795a185ad1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x55795be83550, 0x55795ce465e0, 0x1411, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005efb0 sp=0xc00005ef90 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc00005efe0 sp=0xc00005efb0 pc=0x55795a15910b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x55795a185ad1
created by runtime.init.6
	/usr/lib/golang/src/runtime/proc.go:242 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55795be83550, 0x55795ce48980, 0x140c, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005f7a8 sp=0xc00005f788 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.bgsweep(0xc000086000)
	/usr/lib/golang/src/runtime/mgcsweep.go:89 +0x135 fp=0xc00005f7d8 sp=0xc00005f7a8 pc=0x55795a14b4d5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005f7e0 sp=0xc00005f7d8 pc=0x55795a185ad1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:210 +0x5e

goroutine 4 [runnable]:
runtime.gopark(0x55795be83550, 0x55795ce48f60, 0x55795a121313, 0x2)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005fef0 sp=0xc00005fed0 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.scavengeSleep(0x1d6942, 0x55795ce48f01)
	/usr/lib/golang/src/runtime/mgcscavenge.go:276 +0xf0 fp=0xc00005ff40 sp=0xc00005fef0 pc=0x55795a14a9a0
runtime.bgscavenge(0xc000086000)
	/usr/lib/golang/src/runtime/mgcscavenge.go:400 +0x2e4 fp=0xc00005ffd8 sp=0xc00005ff40 pc=0x55795a14acc4
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005ffe0 sp=0xc00005ffd8 pc=0x55795a185ad1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:211 +0x80

goroutine 18 [finalizer wait]:
runtime.gopark(0x55795be83550, 0x55795ce74e38, 0x1410, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005e758 sp=0xc00005e738 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:175 +0xa7 fp=0xc00005e7e0 sp=0xc00005e758 pc=0x55795a141267
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x55795a185ad1
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:156 +0x63

goroutine 19 [syscall]:
runtime.notetsleepg(0x55795ce5be40, 0x129b9a67c, 0x0)
	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc00005a760 sp=0xc00005a730 pc=0x55795a1338c8
runtime.timerproc(0x55795ce5be20)
	/usr/lib/golang/src/runtime/time.go:311 +0x2f5 fp=0xc00005a7d8 sp=0xc00005a760 pc=0x55795a176615
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005a7e0 sp=0xc00005a7d8 pc=0x55795a185ad1
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 8 [timer goroutine (idle)]:
runtime.gopark(0x55795be83550, 0x55795ce5bda0, 0x1415, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000350760 sp=0xc000350740 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.timerproc(0x55795ce5bda0)
	/usr/lib/golang/src/runtime/time.go:303 +0x27f fp=0xc0003507d8 sp=0xc000350760 pc=0x55795a17659f
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003507e0 sp=0xc0003507d8 pc=0x55795a185ad1
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x55795be833e8, 0xc0003a4040, 0x55795a121418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005b760 sp=0xc00005b740 pc=0x55795a159266
runtime.gcBgMarkWorker(0xc00004e500)
	/usr/lib/golang/src/runtime/mgc.go:1846 +0x105 fp=0xc00005b7d8 sp=0xc00005b760 pc=0x55795a144cb5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005b7e0 sp=0xc00005b7d8 pc=0x55795a185ad1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1794 +0x79

goroutine 26 [GC worker (idle)]:
runtime.gopark(0x55795be833e8, 0xc000046790, 0x55795a121418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000350f60 sp=0xc000350f40 pc=0x55795a159266
runtime.gcBgMarkWorker(0xc000050a00)
	/usr/lib/golang/src/runtime/mgc.go:1846 +0x105 fp=0xc000350fd8 sp=0xc000350f60 pc=0x55795a144cb5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000350fe0 sp=0xc000350fd8 pc=0x55795a185ad1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1794 +0x79

goroutine 40 [syscall]:
runtime.notetsleepg(0x55795ce75640, 0xffffffffffffffff, 0x0)
	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000351798 sp=0xc000351768 pc=0x55795a1338c8
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e fp=0xc0003517c0 sp=0xc000351798 pc=0x55795a16dc8e
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc0003517e0 sp=0xc0003517c0 pc=0x55795a767524
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003517e8 sp=0xc0003517e0 pc=0x55795a185ad1
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43

goroutine 41 [GC worker (idle)]:
runtime.gopark(0x55795be833e8, 0xc0003a4030, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000351f60 sp=0xc000351f40 pc=0x55795a159266
runtime.gcBgMarkWorker(0xc00004c000)
	/usr/lib/golang/src/runtime/mgc.go:1846 +0x105 fp=0xc000351fd8 sp=0xc000351f60 pc=0x55795a144cb5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000351fe0 sp=0xc000351fd8 pc=0x55795a185ad1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1794 +0x79

goroutine 42 [GC worker (idle)]:
runtime.gopark(0x55795be833e8, 0xc0003a4050, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000352760 sp=0xc000352740 pc=0x55795a159266
runtime.gcBgMarkWorker(0xc000052f00)
	/usr/lib/golang/src/runtime/mgc.go:1846 +0x105 fp=0xc0003527d8 sp=0xc000352760 pc=0x55795a144cb5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003527e0 sp=0xc0003527d8 pc=0x55795a185ad1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1794 +0x79

goroutine 43 [chan receive]:
runtime.gopark(0x55795be83550, 0xc000396bf8, 0x7f2774c7170e, 0x3)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000060ed0 sp=0xc000060eb0 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.chanrecv(0xc000396ba0, 0xc000060fb0, 0xc00052a701, 0xc000396ba0)
	/usr/lib/golang/src/runtime/chan.go:524 +0x2ec fp=0xc000060f60 sp=0xc000060ed0 pc=0x55795a12e25c
runtime.chanrecv2(0xc000396ba0, 0xc000060fb0, 0x55795a811fbb)
	/usr/lib/golang/src/runtime/chan.go:411 +0x2b fp=0xc000060f90 sp=0xc000060f60 pc=0x55795a12df5b
github.com/containers/libpod/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x55795ce49fa0)
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:990 +0x8d fp=0xc000060fd8 sp=0xc000060f90 pc=0x55795a910ecd
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000060fe0 sp=0xc000060fd8 pc=0x55795a185ad1
created by github.com/containers/libpod/vendor/k8s.io/klog.init.0
	/builddir/build/BUILD/libpod-5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26/_build/src/github.com/containers/libpod/vendor/k8s.io/klog/klog.go:404 +0x6e

goroutine 51 [timer goroutine (idle)]:
runtime.gopark(0x55795be83550, 0x55795ce5bf20, 0x1415, 0x1)
	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00034e760 sp=0xc00034e740 pc=0x55795a159266
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
runtime.timerproc(0x55795ce5bf20)
	/usr/lib/golang/src/runtime/time.go:303 +0x27f fp=0xc00034e7d8 sp=0xc00034e760 pc=0x55795a17659f
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00034e7e0 sp=0xc00034e7d8 pc=0x55795a185ad1
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/golang/src/runtime/time.go:169 +0x110
[1]    158589 abort (core dumped)  podman build Dockerfile
```

**Describe the results you expected:**

Some warning to use the -f flag or invalid argument. 

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 9adfe850ef954416ea5dd0438d428a60f2139473'
  Distribution:
    distribution: '"rhel"'
    version: "8.2"
  MemFree: 13400088576
  MemTotal: 16334602240
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: ip-172-31-23-38.eu-central-1.compute.internal
  kernel: 4.18.0-193.el8.x86_64
  os: linux
  rootless: false
  uptime: 307h 57m 18.44s (Approximately 12.79 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-12.module+el8.2.0+6669+dde598ec.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```AWS, RHEL8.2 4.18.0-193.el8.x86_64 ```

**Comment by rhatdan** [comment]
Should be fixed in podman-1.9 which will be shipping in RHEL8.2.1 in a couple of weeks.
